### ISSUE TITLE
error on sax update

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#101]
all analyzers report this error. backend is at latest revision.

```
UPDATE ERROR thailand/sax : Traceback (most recent call last):
File "/data/project/osmose/frontend/control.py", line 218, in send_update
tools.update.update(sources[s], url, remote_ip=remote_ip)
File "/data/project/osmose/frontend/tools/update.py", line 102, in update
parser.parse(f)
File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
xmlreader.IncrementalParser.parse(self, source)
File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
self.feed(buffer)
File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
self._parser.Parse(data, isFinal)
File "/usr/lib/python2.7/xml/sax/expatreader.py", line 307, in end_element
self._cont_handler.endElement(name)
File "/data/project/osmose/frontend/tools/update.py", line 278, in endElement
self._class_item[self._class_id],
KeyError: 4061
```

**Comment by jocelynj** [comment]
It is caused by a new plugin, pushed on 325c7ebc8df6661754027e8f894d7bfa9468c3eb.

**Comment by jocelynj** [comment]
Thanks for reporting the issue - it should now be fixed.

**Comment by stephankn** [comment]
confirmed, error is gone. re-running analyzers. Thanks for the quick fix.
