### ISSUE TITLE
error on analyse sax, KeyError: 'natural'

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#1093]
latest docker version
osmose backend version: v1.2-2020-04-26-537-ge6fbb7ab

2021-01-10 21:57:04   Analysing file /data/work/osmose/extracts/china_xinjiang.osm.pbf
[INFO] Reading the file/data/work/osmose/extracts/china_xinjiang.osm.pbf
2021-01-10 21:59:28   error: Fail on <bound method TagRemove_Incompatibles.way of <plugins.TagRemove_Incompatibles.TagRemove_Incompatibles object at 0x7f60616f02d0>> with {'id': 829681835, 'tag': {'amenity': 'fountain', 'leisure': 'swimming_pool', 'name': '音乐喷泉', 'natural': 'water'}, 'nd': [7743820294, 7743820293, 7743820292, 7743820291, 7743820294]}, {'amenity': 'fountain', 'leisure': 'swimming_pool', 'name': '音乐喷泉', 'natural': 'water'}, [7743820294, 7743820293, 7743820292, 7743820291, 7743820294]
2021-01-10 21:59:28   Closing reader and parser
2021-01-10 21:59:28   error: error on analyse sax...
2021-01-10 21:59:28     Traceback (most recent call last):
2021-01-10 21:59:28       File "./osmose_run.py", line 262, in execc
2021-01-10 21:59:28         analyser_obj.analyser()
2021-01-10 21:59:28       File "/opt/osmose-backend/analysers/analyser_sax.py", line 69, in analyser
2021-01-10 21:59:28         self._run_analyse()
2021-01-10 21:59:28       File "/opt/osmose-backend/analysers/analyser_sax.py", line 491, in _run_analyse
2021-01-10 21:59:28         self.parser.CopyTo(self)
2021-01-10 21:59:28       File "/opt/osmose-backend/modules/OsmPbf_libosmbf.py", line 85, in CopyTo
2021-01-10 21:59:28         osm_pbf_parser.read_osm_pbf(self._pbf_file, self)
2021-01-10 21:59:28       File "/opt/osmose-backend/modules/OsmPbf_libosmbf.py", line 109, in way
2021-01-10 21:59:28         self._output.WayCreate(data)
2021-01-10 21:59:28       File "/opt/osmose-backend/analysers/analyser_sax.py", line 238, in WayCreate
2021-01-10 21:59:28         res = meth(data, tags, nds)
2021-01-10 21:59:28       File "/opt/osmose-backend/plugins/TagRemove_Incompatibles.py", line 118, in way
2021-01-10 21:59:28         return self.node(data, tags)
2021-01-10 21:59:28       File "/opt/osmose-backend/plugins/TagRemove_Incompatibles.py", line 106, in node
2021-01-10 21:59:28         conflict.remove(k1)
2021-01-10 21:59:28     KeyError: 'natural'

**Comment by frodrigo** [comment]
Fixed. Thank you for report.
