### ISSUE TITLE
MergeFuel-IT fail to build

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1099]
@fansanelli, please can you look at the fail of MergeFuel-IT update.

[http://osmose.openstreetmap.fr/fr/control/update_matrix?country=italy*](http://osmose.openstreetmap.fr/fr/control/update_matrix?country=italy*)

https://buildbot.osmose.openstreetmap.fr/#/builders/431/builds/145/steps/1/logs/stdio

```
2021-01-12 10:30:06   error: error on analyse merge_fuel_IT...
2021-01-12 10:30:06     Traceback (most recent call last):
2021-01-12 10:30:06       File "./osmose_run.py", line 262, in execc
2021-01-12 10:30:06         analyser_obj.analyser()
2021-01-12 10:30:06       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 193, in analyser
2021-01-12 10:30:06         self.analyser_osmosis_common()
2021-01-12 10:30:06       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1034, in analyser_osmosis_common
2021-01-12 10:30:06         table = self.load.run(self, self.parser, self.mapping, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2021-01-12 10:30:06       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 725, in run
2021-01-12 10:30:06         header = parser.header()
2021-01-12 10:30:06       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 448, in header
2021-01-12 10:30:06         self.f = self.source.open()
2021-01-12 10:30:06       File "/data/project/osmose/backend/analysers/analyser_merge_fuel_IT.py", line 98, in open
2021-01-12 10:30:06         return open(downloader.update_cache('join://' + self.source.fileUrl, 60, self.fetch))
2021-01-12 10:30:06       File "/data/project/osmose/backend/modules/downloader.py", line 98, in update_cache
2021-01-12 10:30:06         if not fetch(url, tmp_file, date_string):
2021-01-12 10:30:06       File "/data/project/osmose/backend/analysers/analyser_merge_fuel_IT.py", line 113, in fetch
2021-01-12 10:30:06         if (impianto & carburante) != 0:
2021-01-12 10:30:06     TypeError: unsupported operand type(s) for &: 'int' and 'NoneType'
2021-01-12 10:30:06   
```

**Comment by frodrigo** [comment]
Results fixed

**Comment by fansanelli** [comment]
Nice ☺️

Thanks
