### ISSUE TITLE
country canada_quebec : cannot run analyse 

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#110]
psycopg2.OperationalError: FATAL:  la base de données « osmose_canada_quebec » n'existe pas

**Comment by frodrigo** [comment]
Where this error come from ?

**Comment by didier2020** [comment]
after
osmose_run.py --cron --country canada_quebec
=>
2016-05-07 16:33:22   load analyser_osmosis_parking_highway
2016-05-07 16:33:22   check database
Traceback (most recent call last):
  File "./osmose_run.py", line 838, in <module>
    err_code |= run(country_conf, logger, options)
  File "./osmose_run.py", line 505, in run
    if not check_database(conf, logger):
  File "./osmose_run.py", line 147, in check_database
    gisconn = psycopg2.connect(conf.db_string)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  la base de données « osmose_canada_quebec » n'existe pas

**Comment by frodrigo** [comment]
Check the default config file. Quebec is configured with the special diff mode. You have to setup Quebec DB first. Or change the config the run it as standard.

**Comment by didier2020** [comment]
ok .

**Comment by didier2020** [comment]
i've "commented" the 2 lines in config file, it's now ok.
