### ISSUE TITLE
Running tests results in ImportError

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1139]
I tried to follow https://github.com/osm-fr/osmose-backend/blob/master/CONTRIBUTING.md#tests

`ImportError: attempted relative import with no known parent package`

```
mateusz@grima:~/Documents/install_moje/OSM software/osmose-backend$ ./tools/pytest.sh sax
Traceback (most recent call last):
  File "analysers/analyser_sax.py", line 23, in <module>
    from .Analyser import Analyser
ImportError: attempted relative import with no known parent package
```

**Comment by matkoniecz** [comment]
I see now that #1064 is mentioning Docker - should I run this from it within Docker virtualization?

**Comment by frodrigo** [comment]
Yes. Use osmose backend docker to have quickly a working environment.

**Comment by jocelynj** [comment]
Even without using docker, it should work, as it is the setup I'm using here.
Maybe you are using an incorrect version of python3 or pytest?

**Comment by matkoniecz** [comment]
Something is definitely going wrong, now I get a different error:

```
mateusz@grima:~/Documents/install_moje/OSM software/osmose-backend$ ./tools/pytest.sh sax
Traceback (most recent call last):
  File "/home/mateusz/.local/bin/pytest", line 5, in <module>
    from pytest import console_main
ModuleNotFoundError: No module named 'pytest'
mateusz@grima:~/Documents/install_moje/OSM software/osmose-backend$ cat /home/mateusz/.local/bin/pytest
#!/usr/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from pytest import console_main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(console_main())
mateusz@grima:~/Documents/install_moje/OSM software/osmose-backend$ python3.9
Python 3.9.0+ (default, Oct 20 2020, 08:43:38) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytest
>>> from pytest import console_main
>>> quit()
mateusz@grima:~/Documents/install_moje/OSM software/osmose-backend$ pytest --version
pytest 6.2.2
```

**Comment by matkoniecz** [comment]
BTW, https://github.com/osm-fr/osmose-backend/blob/master/INSTALL.md#install is incomplete on Ubuntu 20.04.

`sudo apt install ninja-build libarchive-dev extra-cmake-modules flex bison` were needed thanks to PyKOpeningHours
