### ISSUE TITLE
get_millesime check http return code

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1211]
The `get_millesime` function does not check the return of the HTTP query.

```python
        self.init(
            'https://opendata.bordeaux-metropole.fr/explore/dataset/tb_stvel_p',
            'Station VCUB',
            SHP(SourceOpenDataSoft(
                attribution="Bordeaux Métropole",
                url="https://opendata.bordeaux-metropole.fr/explore/dataset/tb_stvel_p",
                format="shp",
                zip="tb_stvel_p.shp")),
```

404: https://opendata.bordeaux-metropole.fr/explore/dataset/tb_stvel_p

```
2021-03-06 03:44:17 france_aquitaine_gironde : merge_bicycle_rental_FR_bm
2021-03-06 03:44:18   error: error on analyse merge_bicycle_rental_FR_bm...
2021-03-06 03:44:18     Traceback (most recent call last):
2021-03-06 03:44:18       File "./osmose_run.py", line 232, in execc
2021-03-06 03:44:18         with obj(analyser_conf, logger.sub()) as analyser_obj:
2021-03-06 03:44:18       File "/data/project/osmose/backend/analysers/analyser_merge_bicycle_rental_FR_bm.py", line 62, in __init__
2021-03-06 03:44:18         "description": lambda res: "VCUB+" if res["tarif"] == "VLS PLUS" else None} )))
2021-03-06 03:44:18       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1125, in init
2021-03-06 03:44:18         self.conflate.mapping.eval_static(self)
2021-03-06 03:44:18       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 987, in eval_static
2021-03-06 03:44:18         self.eval_staticGroup(self.static2, analyser)
2021-03-06 03:44:18       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 981, in eval_staticGroup
2021-03-06 03:44:18         r = colomn(analyser)
2021-03-06 03:44:18       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1130, in source
2021-03-06 03:44:18         return a.parser.source.as_tag_value()
2021-03-06 03:44:18       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 426, in as_tag_value
2021-03-06 03:44:18         return " - ".join(filter(lambda x: x is not None, [self.attribution, self._get_millesime()]))
2021-03-06 03:44:18       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 412, in _get_millesime
2021-03-06 03:44:18         self.millesime = self.get_millesime()
2021-03-06 03:44:18       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 479, in get_millesime
2021-03-06 03:44:18         last_modified = downloader.get("%s/api/datasets/1.0/%s" % (self.base_url, self.dataset)).json()["metas"]["data_processed"]
2021-03-06 03:44:18     KeyError: 'metas'
```

(I am already fixing merge_bicycle_rental_FR_bm)

cc @gileri

**Comment by gileri** [comment]
Good catch ! I think using we should handle cache/errors like [update_cache()](https://github.com/osm-fr/osmose-backend/blob/17acb926d906f199debb0c7bd601c76c6fa8a54f/modules/downloader.py#L98-L108) ! try to get the millesime, fall back to the cache and `raise` if there is none.

I'll either piggy back on existing functions such as `update_cache`/`http_get`, or raise exception for non-2XX HTTP statuses. In both cases the exception will be more meaningful.

**Comment by gileri** [comment]
I forgot that I already used a cache for the millesime, so most of my previous comment is moot.
So I just did in the [PR](https://github.com/osm-fr/osmose-backend/pull/1224) a `response.raise_for_status()` earlier than the subsequent json parsing failure, or `KeyError`.
