### ISSUE TITLE
merge_fuel_IT CSV no more working

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1440]
```
2022-04-22 18:14:59 italy_piemonte : merge_fuel_IT
2022-04-22 18:14:59   run osmosis all analyser Analyser_Merge_Fuel_IT
2022-04-22 18:14:59   Analyser_Merge.py:1154 sql
2022-04-22 18:14:59   Analyser_Merge.py:774 sql
2022-04-22 18:14:59   Analyser_Merge.py:779 sql
2022-04-22 18:14:59   Load source into database
2022-04-22 18:14:59   Analyser_Merge.py:782 sql
2022-04-22 18:15:00   Analyser_Merge.py:790 sql
2022-04-22 18:15:00   Analyser_Merge.py:792 sql
2022-04-22 18:15:00   error: error on analyse merge_fuel_IT...
2022-04-22 18:15:00     Traceback (most recent call last):
2022-04-22 18:15:00       File "/data/project/osmose/backend/./osmose_run.py", line 263, in execc
2022-04-22 18:15:00         analyser_obj.analyser()
2022-04-22 18:15:00       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 193, in analyser
2022-04-22 18:15:00         self.analyser_osmosis_common()
2022-04-22 18:15:00       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1155, in analyser_osmosis_common
2022-04-22 18:15:00         table = self.load.run(self, self.parser, self.conflate, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2022-04-22 18:15:00       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 793, in run
2022-04-22 18:15:00         parser.import_(table, self.srid, osmosis)
2022-04-22 18:15:00       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 548, in import_
2022-04-22 18:15:00         osmosis.giscurs.copy_expert(copy, self.f)
2022-04-22 18:15:00     psycopg2.errors.BadCopyFileFormat: extra data after last expected column
2022-04-22 18:15:00     CONTEXT:  COPY fuel_it, line 31: "23777,ALFONSO DI BENEDETTO CARBURANTI LUBRIFICANTI SRL,Sicilpetroli,Stradale,A. Di Benedetto srl V.l..."
2022-04-22 18:15:00     
```

The intermediate CSV seam invalid.

@fansanelli are you interested on looking at this ?

**Comment by fansanelli** [comment]
Dear Frédéric,

the file is not a valid CSV anymore... Hoping it will be fixed, I wrote to MISE and you are in cc.
We could skip invalid rows for now if you think it's fine.

Francesco

**Comment by fansanelli** [comment]
@frodrigo the file have been updated, can you please delete the cached copies and make the analysis run?
Please let me know if it works
Cheers
Francesco

**Comment by frodrigo** [comment]
@jocelynj can you remove the files from the using
```
grep -L 'www.mise.gov.it' *.url | sed -e 's/.url//' | xargs rm
```

**Comment by jocelynj** [comment]
I've remove all these files on OSM-FR backends.

**Comment by fansanelli** [comment]
@frodrigo @jocelynj It seems working again, can you confirm no more errors are thrown?
Many thanks
Cheers
Francesco

**Comment by frodrigo** [comment]
Yes. Every thing are up to date.
Thank all.
