### ISSUE TITLE
merge_power_plant_FR - NoneType

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1588]
Error when processing France

```
2022-10-03 03:57:19   error: res=[[None, None], 'MICRO CENTRALE OO', '17W000000396446Q', None, '31404', 'Oô', '200072635', 'CC Pyrénées Haut Garonnaises', '31', 'Haute-Garonne', '76', 'Occitanie', None, '31404', None, '22/08/2013', None, '22/08/2013', '23/03/2022', 'L.OO', 'HTA', 'Direct', 'HYDLQ', 'Hydraulique', None, None, None, None, 'FIL.E', "Fil de l'eau", '400.0', None, None, '400.0', None, '1', 'En service', '0.0', '0.0', '0.0', '0.0', '0.0', '17X100A100A0001A', 'Enedis', '1653204', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
2022-10-03 03:57:19   error: ret=None
2022-10-03 03:57:19   error: error on analyse merge_power_plant_FR...
2022-10-03 03:57:19     Traceback (most recent call last):
2022-10-03 03:57:19       File "./osmose_run.py", line 263, in execc
2022-10-03 03:57:19         analyser_obj.analyser()
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 193, in analyser
2022-10-03 03:57:19         self.analyser_osmosis_common()
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1369, in analyser_osmosis_common
2022-10-03 03:57:19         table = super().analyser_osmosis_common()
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1213, in analyser_osmosis_common
2022-10-03 03:57:19         table = self.load.run(self, self.conflate, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 974, in run
2022-10-03 03:57:19         return super().run(osmosis, conflate, db_schema, default_table_base_name, version)
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 880, in run
2022-10-03 03:57:19         osmosis.run0((sql01_ref if conflate.osmRef != "NULL" else sql01_geo).format(table = table, geom = self.geom, validationGeomSQL = self.validationGeomSQL, where = Select.where_attributes(self.select), distinct = distinct, order_by = order_by), insertOfficial)
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 454, in run0
2022-10-03 03:57:19         self.run00(sql, callback)
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 445, in run00
2022-10-03 03:57:19         ret = callback(res)
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 854, in insertOfficial
2022-10-03 03:57:19         res = self.map(res)
2022-10-03 03:57:19       File "/data/project/osmose/backend/analysers/analyser_merge_power_plant_FR.py", line 46, in <lambda>
2022-10-03 03:57:19         float(res["_geom"][0]) + (Stablehash.stablehash(str(res)) % 200 - 100) * 0.00001,
2022-10-03 03:57:19     TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by frodrigo** [comment]
cc @flacombe

**Comment by flacombe** [comment]
Thanks @frodrigo I was about to have a look to that.

Surprizingly I didn't have any geocoding problem.
Will have this in mind to improve geocoding in #1500

**Comment by frodrigo** [comment]
I also see no error. But I made a fix anyway. Maybe a temporary issue with the data.
"Fix", not deployed yet.

**Comment by frodrigo** [comment]
We got it
http://osmose.openstreetmap.fr/en/issues/open?item=8270

**Comment by flacombe** [comment]
Sounds good to me !

I've had a look at results and it's always correct.
Had you done anything regarding the geocoding? Results looks way better than before.

Thank you anyway for fixes, it rocks
