### ISSUE TITLE
Update needed for analyser_merge_charging_station_FR.py

### ISSUE THREAD

**Issue by nlehuby** [osm-fr/osmose-backend#1621]
A new version of the schema used to share the charging_stations has been released: some columns does not have the same name (and there is a few additional info that we can add to OSM).
So the analyser needs to be updated

More info at https://github.com/Jungle-Bus/ref-EU-EVSE/issues/1

**Comment by frodrigo** [comment]
#1622

**Comment by frodrigo** [comment]
It fails with `KeyError: 'nom_operateur'`


https://buildbot.osmose.openstreetmap.fr/#/builders/699/builds/795/steps/2/logs/stdio

```
2022-10-27 20:28:26 france_local_db : merge_charging_station_FR
2022-10-27 20:28:27   run osmosis all analyser Analyser_Merge_Charging_station_FR
2022-10-27 20:28:27   Analyser_Merge.py:1198 sql
2022-10-27 20:28:28   Analyser_Merge.py:795 sql
2022-10-27 20:28:28   Analyser_Merge.py:807 sql
2022-10-27 20:28:28   Load raw data into database
2022-10-27 20:28:28   Analyser_Merge.py:820 sql
2022-10-27 20:28:28   Analyser_Merge.py:825 sql
2022-10-27 20:28:28   Convert raw data to tags
2022-10-27 20:28:28   Analyser_Merge.py:831 sql
2022-10-27 20:28:28   Analyser_Merge.py:832 sql
2022-10-27 20:28:28   Analyser_Merge.py:865 sql
2022-10-27 20:28:29   error: res=[['-1.5127680638813583', '43.48396450961844'], None, None, 'MOBIVE', None, 'Parking Quintaou', '1 allée de Quintaou, Anglet', '64024', '1', '-1.5127680638813583', '43.48396450961844', 'https://www.data.gouv.fr/fr/datasets/localisation-des-infrastructures-de-recharge-pour-vehicules-electriques-irve-sur-la-commune-danglet/#resource-198eaabe-5f9c-4f91-998a-b3c3cb615e52', None, None, '0', "['Type 2 et prise domestique', 'Type 2 et prise domestique']", '0', '0', '0', '0', '0']
2022-10-27 20:28:29   error: ret=None
2022-10-27 20:28:29   error: error on analyse merge_charging_station_FR...
2022-10-27 20:28:29     Traceback (most recent call last):
2022-10-27 20:28:29       File "./osmose_run.py", line 271, in execc
2022-10-27 20:28:29         analyser_obj.analyser()
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 193, in analyser
2022-10-27 20:28:29         self.analyser_osmosis_common()
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1356, in analyser_osmosis_common
2022-10-27 20:28:29         table = super().analyser_osmosis_common()
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1200, in analyser_osmosis_common
2022-10-27 20:28:29         table = self.load.run(self, self.conflate, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 961, in run
2022-10-27 20:28:29         return super().run(osmosis, conflate, db_schema, default_table_base_name, version)
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 865, in run
2022-10-27 20:28:29         osmosis.run0((sql01_ref if conflate.osmRef != "NULL" else sql01_geo).format(table = table, geom = self.geom, validationGeomSQL = self.validationGeomSQL, where = Select.where_attributes(self.select), distinct = distinct, order_by = order_by), insertOfficial)
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 455, in run0
2022-10-27 20:28:29         self.run00(sql, callback)
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 446, in run00
2022-10-27 20:28:29         ret = callback(res)
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 847, in insertOfficial
2022-10-27 20:28:29         tags = conflate.mapping.tagFactory(res)
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1096, in tagFactory
2022-10-27 20:28:29         tags = self.tagFactoryGroup(res, self.static1, self.mapping1)
2022-10-27 20:28:29       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1090, in tagFactoryGroup
2022-10-27 20:28:29         elif colomn and res[colomn]:
2022-10-27 20:28:29     KeyError: 'nom_operateur'
2022-10-27 20:28:29 france_local_db : merge_natural_FR
```

**Comment by frodrigo** [comment]
cc @PanierAvide

**Comment by PanierAvide** [comment]
Hmm... `nom_operateur` is only used in `mapping1` without any specific processing in the analyser. Could the issue be caused by another part of Osmose ?

**Comment by frodrigo** [comment]
> Hmm... `nom_operateur` is only used in `mapping1` without any specific processing in the analyser. Could the issue be caused by another part of Osmose ?

Means the column is not found in the data.
But it is a cache issue. I reset the cache and should be ok tomorrow.

**Comment by PanierAvide** [comment]
Yes the format of remote file has changed (for reference https://github.com/Jungle-Bus/ref-EU-EVSE/pull/2 ). Thanks for your time :wink:

**Comment by frodrigo** [comment]
Bug up in new data https://osmose.openstreetmap.fr/en/issues/graph.png?item=8410

It works.
