### ISSUE TITLE
Opening_Hours issue with sax TagFix_Opening_Hours&ConditionalRestrictions in docker

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#1660]
Running sax on iceland with https://github.com/osm-fr/osmose-backend/commit/762cf0fcedd4940e577e2ac4872713c46278d9b4 produce an error

```
2022-11-23 16:47:19   run sax all
2022-11-23 16:47:20   Analysing file /data/work/osmose/extracts/iceland.osm.pbf
[INFO] Reading the file/data/work/osmose/extracts/iceland.osm.pbf
2022-11-23 16:48:31   error: Fail on <bound method ConditionalRestrictions.way of <plugins.ConditionalRestrictions.ConditionalRestrictions object at 0x7fc6f3ac4f70>> with {'id': 4370534, 'tag': {'access': 'yes', 'amenity': 'parking', 'fee': 'no', 'fee:conditional': 'yes @ (Mo-Fr 10:00-18:00;Sa 10:00-16:00)', 'parking': 'surface', 'supervised': 'no'}, 'nd': [26646798, 26646793, 26646794, 26646796, 26646798]}, {'access': 'yes', 'amenity': 'parking', 'fee': 'no', 'fee:conditional': 'yes @ (Mo-Fr 10:00-18:00;Sa 10:00-16:00)', 'parking': 'surface', 'supervised': 'no'}, [26646798, 26646793, 26646794, 26646796, 26646798]
2022-11-23 16:48:32   Closing reader and parser
2022-11-23 16:48:32   error: error on analyse sax...
2022-11-23 16:48:32     Traceback (most recent call last):
2022-11-23 16:48:32       File "/opt/osmose-backend/./osmose_run.py", line 271, in execc
2022-11-23 16:48:32         analyser_obj.analyser()
2022-11-23 16:48:32       File "/opt/osmose-backend/analysers/analyser_sax.py", line 69, in analyser
2022-11-23 16:48:32         self._run_analyse()
2022-11-23 16:48:32       File "/opt/osmose-backend/analysers/analyser_sax.py", line 491, in _run_analyse
2022-11-23 16:48:32         self.parser.CopyTo(self)
2022-11-23 16:48:32       File "/opt/osmose-backend/modules/OsmPbf_libosmbf.py", line 85, in CopyTo
2022-11-23 16:48:32         osm_pbf_parser.read_osm_pbf(self._pbf_file, self)
2022-11-23 16:48:32       File "/opt/osmose-backend/modules/OsmPbf_libosmbf.py", line 109, in way
2022-11-23 16:48:32         self._output.WayCreate(data)
2022-11-23 16:48:32       File "/opt/osmose-backend/analysers/analyser_sax.py", line 238, in WayCreate
2022-11-23 16:48:32         res = meth(data, tags, nds)
2022-11-23 16:48:32       File "/opt/osmose-backend/plugins/ConditionalRestrictions.py", line 176, in way
2022-11-23 16:48:32         if not sanitized['isValid']:
2022-11-23 16:48:32     TypeError: 'NoneType' object is not subscriptable
```

**Comment by Famlam** [comment]
Seems that for some reason the kopeninghours plugin didn't load succesfully. Can you check if it works if you change this line to
`if sanitized and not sanitized['isValid']:`
https://github.com/osm-fr/osmose-backend/blob/master/plugins/ConditionalRestrictions.py#L176

**Comment by Marc-marc-marc** [comment]
I have changed L176 from
`if not sanitized['isValid']:`
into
` if sanitized and not sanitized['isValid']:`
test ongoing, let's see if it detect the issue (and then trying to find out why kopeninghours didn't load)

**Comment by Marc-marc-marc** [comment]
tested with `docker-compose run --rm backend ./osmose_run.py --country=iceland --resume --analyser=sax --plugin=ConditionalRestrictions --skip-upload --skip-init`

2022-11-24 20:30:00 loading analyses 
2022-11-24 20:30:00   load sax
2022-11-24 20:30:00   check database
fatal: not a git repository (or any of the parent directories): .git
2022-11-24 20:30:00 iceland : sax
libQt5Core.so.5: cannot open shared object file: No such file or directory
2022-11-24 20:30:01     init ConditionalRestrictions (node, way, relation)
2022-11-24 20:30:01   run sax all
2022-11-24 20:30:01   Analysing file /data/work/osmose/extracts/iceland.osm.pbf
[INFO] Reading the file/data/work/osmose/extracts/iceland.osm.pbf
[INFO] We finished reading the file
2022-11-24 20:30:01   Analyse finished
2022-11-24 20:30:01   Closing reader and parser
2022-11-24 20:30:01     init ConditionalRestrictions (node, way, relation)
2022-11-24 20:30:01   Closing reader and parser


can you add a warning about the not-working OH ?

**Comment by Famlam** [comment]
> can you add a warning about the not-working OH ?

What do you mean? In principle, there should be a warning outputted by the TagFix_Opening_Hours plugin when kopeninghours fails to load:
https://github.com/osm-fr/osmose-backend/blob/3dfa8323928d0b89ac592e948b62352ee33b239f/plugins/TagFix_Opening_Hours.py#L25-L30
Maybe running that one will give a clue. (I have more time this weekend, then I could also give it a try if you like)
(Note that ConditionalRestrictions uses the code from TagFix_Opening_Hours)

E.g.: `docker-compose run --rm backend ./osmose_run.py --country=iceland --resume --analyser=sax --plugin=TagFix_Opening_Hours --plugin=ConditionalRestrictions --skip-upload --skip-init`

**Comment by Marc-marc-marc** [comment]
indeed with this cmd, after
`libQt5Core.so.5: cannot open shared object file: No such file or directory`
I got
`2022-11-24 22:13:25     self-disabled TagFix_Opening_Hours
`
it is not very clear that this is a partial error
I suggest :  warning : Opening_Hours not working, self-disabled TagFix_Opening_Hours

here is the output of the build
`Step 11/18 : RUN pip install -r requirements.txt ${PIP_INSTALL}
 ---> Running in 613dcb443ea1
Collecting git+https://invent.kde.org/libraries/kopeninghours.git@v22.08.3 (from -r requirements.txt (line 12))
  Cloning https://invent.kde.org/libraries/kopeninghours.git (to revision v22.08.3) to /tmp/pip-req-build-ywx6rd4o
  Running command git clone --filter=blob:none --quiet https://invent.kde.org/libraries/kopeninghours.git /tmp/pip-req-build-ywx6rd4o
  Running command git checkout -q 07ac9a82da45e7db8b8f3d03c74767e7f9c8fa64
  Resolved https://invent.kde.org/libraries/kopeninghours.git to commit 07ac9a82da45e7db8b8f3d03c74767e7f9c8fa64
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
`

**Comment by Famlam** [comment]
I must say I have trouble reproducing it 🤔.

```
2022-11-25 19:43:18 import post scripts
2022-11-25 19:43:20   OSM data timestamp: 2022-11-24 21:21:51
fatal: not a git repository (or any parent up to mount point /opt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2022-11-25 19:43:20 iceland : sax
2022-11-25 19:43:24     init TagFix_Opening_Hours (node, way, relation)
2022-11-25 19:43:24     init ConditionalRestrictions (node, way, relation)
2022-11-25 19:43:25   run sax all
2022-11-25 19:43:26   Analysing file /data/work/osmose/extracts/iceland.osm.pbf
[INFO] Reading the file/data/work/osmose/extracts/iceland.osm.pbf
[INFO] We finished reading the file
2022-11-25 19:43:31   Analyse finished
2022-11-25 19:43:31   Closing reader and parser
2022-11-25 19:43:31 cleaning :
```
I did use a slightly different approach to include Iceland, maybe this helps?
```patch
- iceland = default_country("europe","iceland", 299133, {"country": "IS", "language": "is", "proj": 32627}) # 299133
- iceland.download["url"] = ""
+ iceland = default_country("europe","iceland", 299133, {"country": "IS", "language": "is", "proj": 32627}, download_repo=GEOFABRIK) # 299133
```

To get the desired logging message, I would suggest to use:
```py
        if not module_PyKOpeningHours:
            logger.warn('module PyKOpeningHours did not load')
            return False
```
instead of 
https://github.com/osm-fr/osmose-backend/blob/3dfa8323928d0b89ac592e948b62352ee33b239f/plugins/TagFix_Opening_Hours.py#L35-L36
This will output:
```
2022-11-25 21:30:47       warning: module PyKOpeningHours did not load
2022-11-25 21:30:47     self-disabled TagFix_Opening_Hours
```

Does this help?

**Comment by Marc-marc-marc** [comment]
I 'll test the improved error message during the day.

the problem doesn't seem to be iceland related, so changing the url method won't solve the problem (but your method is better than mine, do you PR it or do I?)

the problem seems to be simply related to :
- OH compilation problem in docker
`libQt5Core.so.5: cannot open shared object file: No such file or directory``
- using OH when it doesn't work, shouldn't the error be memorized to exit in error at the end of the build, like other error ?

**Comment by Famlam** [comment]
> the problem doesn't seem to be iceland related, so changing the url method won't solve the problem (but your method is better than mine, do you PR it or do I?)

You can PR it: you found the cause, I just changed your fix a bit :)

> your test is also with docker ?

Yes. Before a new test where I want to exclude 'history' effects (OHParser was recently updated, for example), I typically
1. Delete the old docker container
2. Run:
  a. `docker-compose build`
  b. `docker-compose -f docker-compose.yml -f docker-compose-dev.yml run --rm backend`
  c. `cd modules/osm_pbf_parser/ && make && cd -`
  d. Run osmose as usual, e.g. `./osmose_run.py --no-clean --skip-frontend-check --skip-upload --plugin=TagFix_Opening_Hours --plugin=ConditionalRestrictions --country=iceland --analyser=sax` (and --skip-init on subsequent runs)

**Comment by Marc-marc-marc** [comment]
in a not-docker osmose-backend slave and in docker i find it under `/usr/lib/x86_64-linux-gnu/libQt5Core.so.5`

same issue with monaco with `./osmose_run.py --country=monaco --analyser=sax --plugin=TagFix_Opening_Hours --plugin=ConditionalRestrictions --skip-upload`

**Comment by Famlam** [comment]
Hmm, then I don't have any suggestions 🤐. Do you also have access to the dev server? Does it work there?

**Comment by frodrigo** [comment]
Not able to reproduce it neither.
