### ISSUE TITLE
Crash in Highway_Lanes

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-backend#1753]
Looks like the recent change to Highway_Lanes crashes if `turn:lanes` is `reverse|reverse`

```
2023-02-02 22:35:45   error: Fail on <bound method Highway_Lanes.way of <plugins.Highway_Lanes.Highway_Lanes object at 0x7fb4a80b8340>> with {'id': 182357765, 'tag': {'highway': 'trunk_link', 'lanes': '2', 'oneway': 'yes', 'source': 'USGS ortho: imsortho.cr.usgs.gov', 'turn:lanes': 'reverse|reverse'}, 'nd': [1927106755, 4861336845, 1927106756, 2905104616, 822360182, 2905104617, 822360173, 2905104618, 822360045, 2905104619, 822360216]}, {'highway': 'trunk_link', 'lanes': '2', 'oneway': 'yes', 'source': 'USGS ortho: imsortho.cr.usgs.gov', 'turn:lanes': 'reverse|reverse'}, [1927106755, 4861336845, 1927106756, 2905104616, 822360182, 2905104617, 822360173, 2905104618, 822360045, 2905104619, 822360216]
2023-02-02 22:35:45   Closing reader and parser
2023-02-02 22:35:45   error: error on analyse sax...
2023-02-02 22:35:45     Traceback (most recent call last):
2023-02-02 22:35:45       File "osmose_run.py", line 275, in execc
2023-02-02 22:35:45         analyser_obj.analyser()
2023-02-02 22:35:45       File "/srv/osmose/osmose-backend/analysers/analyser_sax.py", line 69, in analyser
2023-02-02 22:35:45         self._run_analyse()
2023-02-02 22:35:45       File "/srv/osmose/osmose-backend/analysers/analyser_sax.py", line 491, in _run_analyse
2023-02-02 22:35:45         self.parser.CopyTo(self)
2023-02-02 22:35:45       File "/srv/osmose/osmose-backend/modules/OsmPbf_libosmbf.py", line 85, in CopyTo
2023-02-02 22:35:45         osm_pbf_parser.read_osm_pbf(self._pbf_file, self)
2023-02-02 22:35:45       File "/srv/osmose/osmose-backend/modules/OsmPbf_libosmbf.py", line 109, in way
2023-02-02 22:35:45         self._output.WayCreate(data)
2023-02-02 22:35:45       File "/srv/osmose/osmose-backend/analysers/analyser_sax.py", line 238, in WayCreate
2023-02-02 22:35:45         res = meth(data, tags, nds)
2023-02-02 22:35:45       File "/srv/osmose/osmose-backend/plugins/Highway_Lanes.py", line 187, in way
2023-02-02 22:35:45         if t[0][0] == "N":
2023-02-02 22:35:45     IndexError: string index out of range
```

**Comment by Famlam** [comment]
I don't see any builders fail with this error anymore, so I think the fix is live :)
