### ISSUE TITLE
`psycopg2.errors.FeatureNotSupported` in analyser_osmosis_building_overlaps

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1903]
See e.g. https://buildbot.osmose.openstreetmap.fr/#/builders/387/builds/965/steps/3/logs/stdio
```
2023-06-13 18:52:52   analyser_osmosis_building_overlaps.py:212 xml generation
2023-06-13 18:52:52   error: sql=
SELECT
    ST_AsText(ST_Transform(ST_Centroid(geom), 4326)),
    ST_Area(geom)
FROM
    (
    SELECT
        (ST_Dump(ST_Union(ST_Buffer(polygon_proj, 200, 'quad_segs=2')))).geom AS geom
    FROM
        intersection__
    WHERE
        intersectionArea > threshold
    ) AS buffer
WHERE
    ST_Area(geom) > 1000 * 1000
2023-06-13 18:52:52   error: error on analyse osmosis_building_overlaps...
2023-06-13 18:52:52     Traceback (most recent call last):
2023-06-13 18:52:52       File "/data/project/osmose/backend/./osmose_run.py", line 275, in execc
2023-06-13 18:52:52         analyser_obj.analyser()
2023-06-13 18:52:52       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 291, in analyser
2023-06-13 18:52:52         self.analyser_osmosis_full()
2023-06-13 18:52:52       File "/data/project/osmose/backend/analysers/analyser_osmosis_building_overlaps.py", line 212, in analyser_osmosis_full
2023-06-13 18:52:52         self.run(sql60.format("", ""), self.callback60)
2023-06-13 18:52:52       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 583, in run
2023-06-13 18:52:52         self.run00(sql, callback_package)
2023-06-13 18:52:52       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 535, in run00
2023-06-13 18:52:52         self.giscurs.execute(sql)
2023-06-13 18:52:52       File "/data/project/osmose/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 146, in execute
2023-06-13 18:52:52         return super().execute(query, vars)
2023-06-13 18:52:52     psycopg2.errors.FeatureNotSupported: A stored procedure tried to use deprecated C function 'pgis_geometry_union_finalfn'
2023-06-13 18:52:52     DETAIL:  Library function 'pgis_geometry_union_finalfn' was deprecated in PostGIS 3.3.0
2023-06-13 18:52:52     HINT:  Consider running: SELECT postgis_extensions_upgrade()
2023-06-13 18:52:52     
```

**Comment by Famlam** [comment]
Closing per message on Matrix: known update issue
