### ISSUE TITLE
building overlaps - changement important du nombre d'erreur 

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#196]
depuis la derniere modification
osmose-backend/analysers/analyser_osmosis_building_overlaps.py

cela ne donne plus du tout les mêmes résulats
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&class=2&start_date=2017-04

http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&class=4&start_date=2017-04

**Comment by frodrigo** [comment]
We make some refactoring
https://github.com/osm-fr/osmose-backend/commit/b23b32785aea68805d0893a4c6f17535d496fc5d

There is now a common way to build a buildings table over all analysers, and we do it only once.
https://github.com/osm-fr/osmose-backend/commit/b23b32785aea68805d0893a4c6f17535d496fc5d#diff-ab07a3bfdc35e28eae02f219e3852ae9R92

In this process we switch from area of degres to area of meters
https://github.com/osm-fr/osmose-backend/commit/b23b32785aea68805d0893a4c6f17535d496fc5d#diff-068ca53e755fe4202c2bd2f2b835e2a0L109
https://github.com/osm-fr/osmose-backend/commit/b23b32785aea68805d0893a4c6f17535d496fc5d#diff-068ca53e755fe4202c2bd2f2b835e2a0L122
https://github.com/osm-fr/osmose-backend/commit/b23b32785aea68805d0893a4c6f17535d496fc5d#diff-068ca53e755fe4202c2bd2f2b835e2a0L138
https://github.com/osm-fr/osmose-backend/commit/b23b32785aea68805d0893a4c6f17535d496fc5d#diff-068ca53e755fe4202c2bd2f2b835e2a0L145

**Comment by frodrigo** [comment]
Same issue here
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&class=1&start_date=2017-04

**Comment by frodrigo** [comment]
Almost all issues are in Russia, and markers are shifted
http://osmose.openstreetmap.fr/fr/map/#item=0&class=4&start_date=2017-04&zoom=18&lat=52.351074&lon=35.814091&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT
Maybe we use a wrong projection.

**Comment by didier2020** [comment]
issues in france :
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=france*

**Comment by didier2020** [comment]
issues = 0 in all this country
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=france_*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=usa_*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=china_*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=india_*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=spain_*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=italy_*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=canada_*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=australia_*
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=0&start_date=2017-04&country=japan*

**Comment by didier2020** [comment]
an other issues since update (today)
2017-05-10 10:32:40 [0;31mrussia_chechen_republic : osmosis_building_overlaps[0m
2017-05-10 10:32:40   run osmosis all analyser Analyser_Osmosis_Building_Overlaps
2017-05-10 10:32:40   requires table buildings
2017-05-10 10:32:40   error on analyse...
2017-05-10 10:32:40     Traceback (most recent call last):
2017-05-10 10:32:40       File "./osmose_run.py", line 639, in run
2017-05-10 10:32:40         analyser_obj.analyser()
2017-05-10 10:32:40       File "./analysers/Analyser_Osmosis.py", line 168, in analyser
2017-05-10 10:32:40         self.requires_tables_build(self.requires_tables_full)
2017-05-10 10:32:40       File "./analysers/Analyser_Osmosis.py", line 236, in requires_tables_build
2017-05-10 10:32:40         self.giscurs.execute(self.sql_create_buildings.format(self.config.db_schema.split(',')[0], self.config.options.get("proj")))
2017-05-10 10:32:40       File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 120, in execute
2017-05-10 10:32:40         return super(DictCursor, self).execute(query, vars)
2017-05-10 10:32:40     InternalError: ERREUR:  transform: couldn't project point (45.7018 43.306 0): latitude or longitude exceeded limits (-14)

**Comment by frodrigo** [comment]
There is no issues, nether in the history, I don't know why. cc @jocelynj 
http://osmose.openstreetmap.fr/fr/errors/?item=0&country=france_*

**Comment by jocelynj** [comment]
Could it be because the new projection used on Russia is limited in lat/lon ?

**Comment by didier2020** [comment]
in sql50
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_building_overlaps.py

line 100 : "buildings.id > bnodes.id AND"
previously it was "buildings.id != bnodes.id"

**Comment by frodrigo** [comment]
Intersection is symmetric. With > we check only whether building 1 intersectrects building 2, but not whether building 2 intercepts building 1.

**Comment by didier2020** [comment]
sql50 is for gap between building - not for intersects.

line 100 : "buildings.id > bnodes.id AND"
previously it was "buildings.id != bnodes.id"

**Comment by frodrigo** [comment]
Same thing for gap, it's symmetric.

**Comment by didier2020** [comment]
an other issues since update (today)
2017-05-12 08:53:25 [0;31mrussia_adygea_republic : osmosis_roundabout_level[0m
2017-05-12 08:53:25   run osmosis all analyser Analyser_Osmosis_Roundabout_Level
2017-05-12 08:53:25   requires table highways
2017-05-12 08:53:25   error on analyse...
2017-05-12 08:53:25     Traceback (most recent call last):
2017-05-12 08:53:25       File "./osmose_run.py", line 639, in run
2017-05-12 08:53:25         analyser_obj.analyser()
2017-05-12 08:53:25       File "./analysers/Analyser_Osmosis.py", line 166, in analyser
2017-05-12 08:53:25         self.requires_tables_build(self.requires_tables_common)
2017-05-12 08:53:25       File "./analysers/Analyser_Osmosis.py", line 222, in requires_tables_build
2017-05-12 08:53:25         self.giscurs.execute(self.sql_create_highways.format(self.config.db_schema.split(',')[0], self.config.options.get("proj")))
2017-05-12 08:53:25       File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 120, in execute
2017-05-12 08:53:25         return super(DictCursor, self).execute(query, vars)
2017-05-12 08:53:25     InternalError: ERREUR:  GetProj4StringSPI: Cannot find SRID (5043) in spatial_ref_sys
2017-05-12 08:53:25

**Comment by didier2020** [comment]
i've tested france_corse and size of all results is 85 octets
decompressed is :
<?xml version="1.0" encoding="UTF-8"?>

**Comment by didier2020** [comment]
all results for france_corse is "<?xml version="1.0" encoding="UTF-8"?>" (in the bz2 file)

**Comment by frodrigo** [comment]
Same probleme with 7011

**Comment by frodrigo** [comment]
The second issue was because analysers output projected coodrs and not lat/lon. ( @jocelynj same problem as the Antarctica issue)

**Comment by didier2020** [comment]
just tested on france_corse, it seems ok.

**Comment by frodrigo** [comment]
Thank.
