### ISSUE TITLE
merge_public_equipment_FR_nantes_toilets fails with `KeyError: 'id'`

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1971]
For exact a month the analyser merge_public_equipment_FR_nantes_toilets has not had a succesful run: 
Log output: https://buildbot.osmose.openstreetmap.fr/#/builders/290/builds/1063/steps/3/logs/stdio

```
2023-07-25 04:36:58 france_pays_de_la_loire_loire_atlantique : merge_public_equipment_FR_nantes_toilets
2023-07-25 04:36:59   run osmosis all analyser Analyser_Merge_Public_Equipment_FR_Nantes_Toilets
2023-07-25 04:36:59   Analyser_Merge.py:1241 sql
2023-07-25 04:36:59   Analyser_Merge.py:831 sql
2023-07-25 04:36:59   Analyser_Merge.py:843 sql
2023-07-25 04:36:59   Load raw data into database
2023-07-25 04:36:59   Analyser_Merge.py:861 sql
2023-07-25 04:36:59   Analyser_Merge.py:866 sql
2023-07-25 04:36:59   Convert raw data to tags
2023-07-25 04:36:59   Analyser_Merge.py:872 sql
2023-07-25 04:36:59   Analyser_Merge.py:873 sql
2023-07-25 04:36:59   Analyser_Merge.py:906 sql
2023-07-25 04:36:59   error: res=[['[-1.6470992624505774,47.19324888126652]', '[-1.6470992624505774,47.19324888126652]'], '2', '2', '1', None, 'Esplanade Alphonse Guihot', '[-1.6470992624505774,47.19324888126652]', '18', 'Loire-Chézine', 'Point', '2', '44074']
2023-07-25 04:36:59   error: ret=None
2023-07-25 04:36:59   error: error on analyse merge_public_equipment_FR_nantes_toilets...
2023-07-25 04:36:59     Traceback (most recent call last):
2023-07-25 04:36:59       File "/data/project/osmose/backend/./osmose_run.py", line 275, in execc
2023-07-25 04:36:59         analyser_obj.analyser()
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 290, in analyser
2023-07-25 04:36:59         self.analyser_osmosis_common()
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1399, in analyser_osmosis_common
2023-07-25 04:36:59         table = super().analyser_osmosis_common()
2023-07-25 04:36:59                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1243, in analyser_osmosis_common
2023-07-25 04:36:59         table = self.load.run(self, self.conflate, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2023-07-25 04:36:59                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1003, in run
2023-07-25 04:36:59         return super().run(osmosis, conflate, db_schema, default_table_base_name, version)
2023-07-25 04:36:59                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 906, in run
2023-07-25 04:36:59         osmosis.run0((sql01_ref if conflate.osmRef != "NULL" else sql01_geo).format(table = table, geom = self.geom, validationGeomSQL = self.validationGeomSQL, where = Select.where_attributes(self.select), distinct = distinct, order_by = order_by), insertOfficial)
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 557, in run0
2023-07-25 04:36:59         self.run00(sql, callback)
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 548, in run00
2023-07-25 04:36:59         ret = callback(res)
2023-07-25 04:36:59               ^^^^^^^^^^^^^
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 888, in insertOfficial
2023-07-25 04:36:59         tags = conflate.mapping.tagFactory(res)
2023-07-25 04:36:59                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1138, in tagFactory
2023-07-25 04:36:59         tags = self.tagFactoryGroup(res, self.static1, self.mapping1)
2023-07-25 04:36:59                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25 04:36:59       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1132, in tagFactoryGroup
2023-07-25 04:36:59         elif colomn and res[colomn]:
2023-07-25 04:36:59                         ~~~^^^^^^^^
2023-07-25 04:36:59     KeyError: 'id'
```

**Comment by frodrigo** [comment]
Yes. I already see the issue but the remote data have the key. I think there is only bad data in the cache. So I was just waiting about cache update.

**Comment by Famlam** [comment]
I suspect it's not the cache, as it's still failing (and the cache is only 30 days, if I'm not mistaken)

**Comment by Famlam** [comment]
Oops I see I filed this twice
#2076
