### ISSUE TITLE
france_mayotte - error on analyse merimee

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#204]
2017-06-02 19:42:23   ./analysers/Analyser_Merge.py:552 sql
('res=', [u'45.113', u'-12.8341', u'01964B', u'CHICONI AP', u'Agence postale commnunale', None, u'AGENCE POSTALE COMMUNALE DE CHICONI', None, u'97670', u'CHICONI', u'FRANCE', u'-12.8341', u'45.113', u'G\xe9ocod\xe9 au num\xe9ro', u'3631', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non'])
('ret=', None)
2017-06-02 19:42:24   error on analyse...
2017-06-02 19:42:24     Traceback (most recent call last):
2017-06-02 19:42:24       File "./osmose_run.py", line 639, in run
2017-06-02 19:42:24         analyser_obj.analyser()
2017-06-02 19:42:24       File "./analysers/Analyser_Osmosis.py", line 171, in analyser
2017-06-02 19:42:24         self.analyser_osmosis_common()
2017-06-02 19:42:24       File "./analysers/Analyser_Merge.py", line 751, in analyser_osmosis_common
2017-06-02 19:42:24         table = self.load.run(self, self.parser, self.mapping, self.config.db_user, self.__class__.__name__.lower()[15:], self.lastUpdate())
2017-06-02 19:42:24       File "./analysers/Analyser_Merge.py", line 592, in run
2017-06-02 19:42:24         osmosis.run0((sql01_ref if mapping.osmRef != "NULL" else sql01_geo) % {"table":table, "x":self.x, "y":self.y, "where":self.formatCSVSelect(), "distinct": distinct, "order_by": order_by}, insertOfficial)
2017-06-02 19:42:24       File "./analysers/Analyser_Osmosis.py", line 364, in run0
2017-06-02 19:42:24         ret = callback(res)
2017-06-02 19:42:24       File "./analysers/Analyser_Merge.py", line 569, in insertOfficial
2017-06-02 19:42:24         tags = mapping.generate.tagFactory(res)
2017-06-02 19:42:24       File "./analysers/Analyser_Merge.py", line 668, in tagFactory
2017-06-02 19:42:24         tags = self.tagFactoryGroup(res, self.static1, self.mapping1)
2017-06-02 19:42:24       File "./analysers/Analyser_Merge.py", line 659, in tagFactoryGroup
2017-06-02 19:42:24         r = colomn(res)
2017-06-02 19:42:24       File "./analysers/analyser_merge_poste_FR.py", line 73, in <lambda>
2017-06-02 19:42:24         "yes" if self.bool[res["Accessibilité_Absence_de_ressaut_de_plus_de_2_cm_de_haut"]] and self.bool[res["Accessibilité_Entrée_autonome_en_fauteuil_roulant_possible"]] else
2017-06-02 19:42:24       File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 144, in __getitem__
2017-06-02 19:42:24         x = self._index[x]
2017-06-02 19:42:24     KeyError: 'Accessibilit\xc3\xa9_Absence_de_ressaut_de_plus_de_2_cm_de_haut'

**Comment by didier2020** [comment]
cool, it fixed.
