### ISSUE TITLE
error on analyse pitch_fr

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#205]
2017-06-02 19:49:42   run osmosis all analyser SubAnalyser_Merge_Pitch_FR_206
2017-06-02 19:49:42   ./analysers/Analyser_Merge.py:512 sql
2017-06-02 19:49:42   Convert data to tags
2017-06-02 19:49:42   ./analysers/Analyser_Merge.py:551 sql
2017-06-02 19:49:42   ./analysers/Analyser_Merge.py:552 sql
2017-06-02 19:49:42   ./analysers/Analyser_Merge.py:598 sql
2017-06-02 19:49:42   ./analysers/Analyser_Merge.py:603 sql
2017-06-02 19:49:42   Empty bbox, abort
2017-06-02 19:49:43   update
2017-06-02 19:49:43     iteration=1
UPDATE ERROR france_mayotte/merge_pitch_FR : Traceback (most recent call last):
  File "/data/project/osmose/frontend/control.py", line 261, in send_update
    tools.update.update(sources[s], save_filename, remote_ip=remote_ip)
  File "/data/project/osmose/frontend/tools/update.py", line 102, in update
    parser.parse(f)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
SAXParseException: /data/work/osmose/results/Analyser_Merge_Pitch_FR-france_mayotte.xml.bz2:31:0: junk after document element
2017-06-02 19:49:44     iteration=1
UPDATE ERROR france_mayotte/merge_pitch_FR : Traceback (most recent call last):
  File "/data/project/osmose/frontend/control.py", line 261, in send_update
    tools.update.update(sources[s], save_filename, remote_ip=remote_ip)
  File "/data/project/osmose/frontend/tools/update.py", line 102, in update
    parser.parse(f)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
SAXParseException: /data/work/osmose/results/Analyser_Merge_Pitch_FR-france_mayotte.xml.bz2:31:0: junk after document element

**Comment by didier2020** [comment]
cool, it fixed.
