### ISSUE TITLE
merge_pitch_FR: column "Nom du bâtiment" does not exist

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2052]
In the logs of the past few weeks, analyser_merge_pitch_FR seems to fail with a query to column "Nom du bâtiment" that doesn't exist anymore.
https://buildbot.osmose.openstreetmap.fr/#/builders/351/builds/1161/steps/3/logs/stdio

```
2023-10-24 13:17:21   error: sql=CREATE TABLE nouvellecad546_pitch_fr_fields AS SELECT "Longitude (WGS84)", "Latitude (WGS84)", "Type d'équipement sportif", "Numéro de l'installation sportive", "Nom de l'installation sportive", "Nom du bâtiment", "Nature du sol" FROM nouvellecad546_pitch_fr
2023-10-24 13:17:21   error: error on analyse merge_pitch_FR...
2023-10-24 13:17:21     Traceback (most recent call last):
2023-10-24 13:17:21       File "/data/project/osmose/backend/./osmose_run.py", line 275, in execc
2023-10-24 13:17:21         analyser_obj.analyser()
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Merge_Dynamic.py", line 45, in analyser
2023-10-24 13:17:21         analyser_obj.analyser()
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 290, in analyser
2023-10-24 13:17:21         self.analyser_osmosis_common()
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1401, in analyser_osmosis_common
2023-10-24 13:17:21         table = super().analyser_osmosis_common()
2023-10-24 13:17:21                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1245, in analyser_osmosis_common
2023-10-24 13:17:21         table = self.load.run(self, self.conflate, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2023-10-24 13:17:21                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1003, in run
2023-10-24 13:17:21         return super().run(osmosis, conflate, db_schema, default_table_base_name, version)
2023-10-24 13:17:21                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 867, in run
2023-10-24 13:17:21         self.parser.import_(table, osmosis)
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 585, in import_
2023-10-24 13:17:21         osmosis.run0("CREATE TABLE {0}_fields AS SELECT {1} FROM {0}".format(
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 557, in run0
2023-10-24 13:17:21         self.run00(sql, callback)
2023-10-24 13:17:21       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 535, in run00
2023-10-24 13:17:21         self.giscurs.execute(sql)
2023-10-24 13:17:21       File "/data/project/osmose/.venvs/backend/lib/python3.11/site-packages/psycopg2/extras.py", line 146, in execute
2023-10-24 13:17:21         return super().execute(query, vars)
2023-10-24 13:17:21                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-24 13:17:21     psycopg2.errors.UndefinedColumn: column "Nom du bâtiment" does not exist
2023-10-24 13:17:21     LINE 1: ...tion sportive", "Nom de l'installation sportive", "Nom du bâ...
2023-10-24 13:17:21                                                                  ^
2023-10-24 13:17:21     
```

**Comment by Famlam** [comment]
I'm confused, the fix should be live already, right?
However, the server still says `2023-11-22 15:42:28     psycopg2.errors.UndefinedColumn: column "Nom du bâtiment" does not exist` even though the code doesn't contain `Nom du bâtiment` anymore

**Comment by frodrigo** [comment]
The backend source code is not updating on osm213
http://osmose.openstreetmap.fr/fr/control/update_summary
- [osm213 ](http://osmose.openstreetmap.fr/fr/control/update_matrix?remote=2a10%3Ac704%3A8004%3A%3A213)(2022-10-09-417 - 2022-10-09-457)

while
- [osm212 ](http://osmose.openstreetmap.fr/fr/control/update_matrix?remote=2a10%3Ac704%3A8004%3A%3A212)(2022-10-09-424 - 2022-10-09-500)

**Comment by frodrigo** [comment]
cc @jocelynj

**Comment by jocelynj** [comment]
The ssh server on osm213 seems to have issues, and there are a log of "defunct" ssh jobs. I'm restarting the host after an apt upgrade.

**Comment by jocelynj** [comment]
It should better now. I've rebased osmose/backend to 18c54db8f17de52aff98fd57c938746e33e2aa6d

**Comment by jocelynj** [comment]
I've also updated and restarted osm211 and osm212.

**Comment by frodrigo** [comment]
Thank you all.
