### ISSUE TITLE
Implement SourceDataFair for analyser_merge_postal_code_FR

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2053]
analyser_merge_postal_code_FR
Error first appeared on 2023-07-23

https://buildbot.osmose.openstreetmap.fr/#/builders/351/builds/1148/steps/3/logs/stdio
```
2023-10-25 16:08:03     Traceback (most recent call last):
2023-10-25 16:08:03       File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
2023-10-25 16:08:03         conn = connection.create_connection(
2023-10-25 16:08:03                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 16:08:03       File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
2023-10-25 16:08:03         for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-10-25 16:08:03                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 16:08:03       File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
2023-10-25 16:08:03         for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-10-25 16:08:03                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-25 16:08:03     socket.gaierror: [Errno -2] Name or service not known

etcetera
```

The following URL https://datanova.legroupe.laposte.fr/explore/dataset/laposte_hexasmal cannot be reached anymore

**Comment by frodrigo** [comment]
The web site moved and no more using `SourceOpenDataSoft`. The new website is based on "data-fair". There is no implementation of `SourceDataFair` for now.

While merge_postal_code_FR is downloadable at once.
It is not the case for merge_poste_FR and merge_post_box_FR, the API send paginated data only.
