### ISSUE TITLE
 psycopg2.errors.FeatureNotSupported: A stored procedure tried to use deprecated C function 'pgis_geometry_union_finalfn'

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2059]
https://buildbot.osmose.openstreetmap.fr/#/builders/722/builds/1020/steps/3/logs/stdio
```
2023-11-01 06:31:35 switzerland_basel_landschaft : osmosis_relation_associatedStreet
2023-11-01 06:31:35   osmosis resume post scripts
2023-11-01 06:31:36   run osmosis base analyser Analyser_Osmosis_Relation_AssociatedStreet
2023-11-01 06:31:36   analyser_osmosis_relation_associatedStreet.py:666 sql
2023-11-01 06:31:36   analyser_osmosis_relation_associatedStreet.py:667 sql
2023-11-01 06:31:36   analyser_osmosis_relation_associatedStreet.py:668 xml generation
2023-11-01 06:31:37   analyser_osmosis_relation_associatedStreet.py:669 xml generation
2023-11-01 06:31:37   analyser_osmosis_relation_associatedStreet.py:671 sql
2023-11-01 06:31:37   analyser_osmosis_relation_associatedStreet.py:672 sql
2023-11-01 06:31:37   analyser_osmosis_relation_associatedStreet.py:673 sql
2023-11-01 06:31:37   analyser_osmosis_relation_associatedStreet.py:674 xml generation
2023-11-01 06:31:37   analyser_osmosis_relation_associatedStreet.py:678 sql
2023-11-01 06:31:37   analyser_osmosis_relation_associatedStreet.py:679 xml generation
2023-11-01 06:31:37   error: sql=
SELECT
    id,
    ST_AsText((SELECT ST_Centroid(ST_Union(linestring)) FROM street_name WHERE t.id = street_name.id)) AS geom,
    string_agg(name, ', ') AS names
FROM
    (SELECT id, name FROM street_name GROUP BY id, name) AS t
GROUP BY
    id
HAVING
    COUNT(*) > 1
2023-11-01 06:31:37   error: error on analyse osmosis_relation_associatedStreet...
2023-11-01 06:31:37     Traceback (most recent call last):
2023-11-01 06:31:37       File "/data/project/osmose/backend/./osmose_run.py", line 265, in execc
2023-11-01 06:31:37         analyser_obj.analyser_resume(remote_timestamp, already_issued_objects)
2023-11-01 06:31:37       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 342, in analyser_resume
2023-11-01 06:31:37         self.analyser_change()
2023-11-01 06:31:37       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 312, in analyser_change
2023-11-01 06:31:37         self.analyser_osmosis_common()
2023-11-01 06:31:37       File "/data/project/osmose/backend/analysers/analyser_osmosis_relation_associatedStreet.py", line 679, in analyser_osmosis_common
2023-11-01 06:31:37         self.run(sql80, lambda res: {"class":7, "subclass":1, "data":[self.relation_full, self.positionAsText], "text":{"en": res[2]}} )
2023-11-01 06:31:37       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 583, in run
2023-11-01 06:31:37         self.run00(sql, callback_package)
2023-11-01 06:31:37       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 535, in run00
2023-11-01 06:31:37         self.giscurs.execute(sql)
2023-11-01 06:31:37       File "/data/project/osmose/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 146, in execute
2023-11-01 06:31:37         return super().execute(query, vars)
2023-11-01 06:31:37     psycopg2.errors.FeatureNotSupported: A stored procedure tried to use deprecated C function 'pgis_geometry_union_finalfn'
2023-11-01 06:31:37     DETAIL:  Library function 'pgis_geometry_union_finalfn' was deprecated in PostGIS 3.3.0
2023-11-01 06:31:37     HINT:  Consider running: SELECT postgis_extensions_upgrade()
2023-11-01 06:31:37     
```

**Comment by frodrigo** [comment]
@jocelynj @Marc-marc-marc we have updated postgis on backend without updating it in database.

This issue report from log from ca-davin02

**Comment by Famlam** [comment]
The first build was successful :) https://buildbot.osmose.openstreetmap.fr/#/builders/722

**Comment by frodrigo** [comment]
It was fixed, and checked on all backends.
