### ISSUE TITLE
france_martinique : merge_poste_FR

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#208]
error on analyse
2017-06-11 17:49:04 france_martinique : merge_poste_FR
2017-06-11 17:49:04   run osmosis all analyser Analyser_Merge_Poste_FR
2017-06-11 17:49:04   ./analysers/Analyser_Merge.py:512 sql
2017-06-11 17:49:04   Load source into database
2017-06-11 17:49:04   ./analysers/Analyser_Merge.py:520 sql
2017-06-11 17:49:04   ./analysers/Analyser_Merge.py:528 sql
2017-06-11 17:49:04   ./analysers/Analyser_Merge.py:530 sql
2017-06-11 17:49:04   ./analysers/Analyser_Merge.py:532 sql
2017-06-11 17:49:04   ./analysers/Analyser_Merge.py:533 sql
2017-06-11 17:49:05   Convert data to tags
2017-06-11 17:49:05   ./analysers/Analyser_Merge.py:551 sql
2017-06-11 17:49:05   ./analysers/Analyser_Merge.py:552 sql
('res=', [u'-61.060782', u'14.624127', u'16557B', u'TEXACO REDOUTE RELAIS POSTE AP', u'Relais poste commer\xe7ant', u'ROUTE DE REDOUTE', u'STATION SERVICE TEXACO', '', u'97200', u'FORT DE FRANCE', u'FRANCE', u'14.624127', u'-61.060782', u'G\xe9ocod\xe9 au num\xe9ro', u'3631', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non', u'Non'])
('ret=', None)
2017-06-11 17:49:09   error on analyse...
2017-06-11 17:49:09     Traceback (most recent call last):
2017-06-11 17:49:09       File "./osmose_run.py", line 639, in run
2017-06-11 17:49:09         analyser_obj.analyser()
2017-06-11 17:49:09       File "./analysers/Analyser_Osmosis.py", line 170, in analyser
2017-06-11 17:49:09         self.analyser_osmosis_common()
2017-06-11 17:49:09       File "./analysers/Analyser_Merge.py", line 751, in analyser_osmosis_common
2017-06-11 17:49:09         table = self.load.run(self, self.parser, self.mapping, self.config.db_user, self.__class__.__name__.lower()[15:], self.lastUpdate())
2017-06-11 17:49:09       File "./analysers/Analyser_Merge.py", line 592, in run
2017-06-11 17:49:09         osmosis.run0((sql01_ref if mapping.osmRef != "NULL" else sql01_geo) % {"table":table, "x":self.x, "y":self.y, "where":self.formatCSVSelect(), "distinct": distinct, "order_by": order_by}, insertOfficial)
2017-06-11 17:49:09       File "./analysers/Analyser_Osmosis.py", line 360, in run0
2017-06-11 17:49:09         ret = callback(res)
2017-06-11 17:49:09       File "./analysers/Analyser_Merge.py", line 569, in insertOfficial
2017-06-11 17:49:09         tags = mapping.generate.tagFactory(res)
2017-06-11 17:49:09       File "./analysers/Analyser_Merge.py", line 668, in tagFactory
2017-06-11 17:49:09         tags = self.tagFactoryGroup(res, self.static1, self.mapping1)
2017-06-11 17:49:09       File "./analysers/Analyser_Merge.py", line 659, in tagFactoryGroup
2017-06-11 17:49:09         r = colomn(res)
2017-06-11 17:49:09       File "./analysers/analyser_merge_poste_FR.py", line 73, in <lambda>
2017-06-11 17:49:09         "yes" if self.bool[res["Accessibilité_Absence_de_ressaut_de_plus_de_2_cm_de_haut"[:50]]] and self.bool[res["Accessibilité_Entrée_autonome_en_fauteuil_roulant_possible"[:50]]] else
2017-06-11 17:49:09       File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 144, in __getitem__
2017-06-11 17:49:09         x = self._index[x]
2017-06-11 17:49:09     KeyError: 'Accessibilit\xc3\xa9_Absence_de_ressaut_de_plus_de_2_cm_'

**Comment by didier2020** [comment]
it's fixed . thanks
