### ISSUE TITLE
Russia_khanty_mansi_autonomous_okrug - error on analyse

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#213]
2017-06-29 14:33:49 russia_khanty_mansi_autonomous_okrug : osmosis_duplicated_geotag
2017-06-29 14:33:49   run osmosis all analyser Analyser_Osmosis_Duplicated_Geotag
2017-06-29 14:33:49   ./analysers/analyser_osmosis_duplicated_geotag.py:177 xml generation
2017-06-29 14:36:30   ./analysers/analyser_osmosis_duplicated_geotag.py:180 sql
2017-06-29 14:36:31   ./analysers/analyser_osmosis_duplicated_geotag.py:181 sql
2017-06-29 14:36:31   ./analysers/analyser_osmosis_duplicated_geotag.py:182 xml generation
2017-06-29 14:36:31   ./analysers/analyser_osmosis_duplicated_geotag.py:184 sql
2017-06-29 14:36:36   ./analysers/analyser_osmosis_duplicated_geotag.py:185 sql
2017-06-29 14:36:39   ./analysers/analyser_osmosis_duplicated_geotag.py:186 xml generation
2017-06-29 14:37:16   ./analysers/analyser_osmosis_duplicated_geotag.py:188 sql
2017-06-29 14:37:16   ./analysers/analyser_osmosis_duplicated_geotag.py:189 sql
2017-06-29 14:37:18   ./analysers/analyser_osmosis_duplicated_geotag.py:190 xml generation
2017-06-29 14:37:40   update
2017-06-29 14:37:40     iteration=1
UPDATE ERROR russia_khanty_mansi_autonomous_okrug/osmosis_duplicated_geotag : Traceback (most recent call last):
  File "/data/project/osmose/frontend/control.py", line 261, in send_update
    tools.update.update(sources[s], save_filename, remote_ip=remote_ip)
  File "/data/project/osmose/frontend/tools/update.py", line 102, in update
    parser.parse(f)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 307, in end_element
    self._cont_handler.endElement(name)
  File "/data/project/osmose/frontend/tools/update.py", line 281, in endElement
    self._error_texts,
  File "/data/project/osmose/frontend/tools/update.py", line 53, in execute_sql
    dbcurs.execute(sql, args)
  File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 120, in execute
    return super(DictCursor, self).execute(query, vars)
OperationalError: index row requires 15824 bytes, maximum size is 8191

**Comment by jocelynj** [comment]
Quite strange ..

Is it systematic with this country ?

Can you send the xml file that should have been uploaded ?  (it should be in osmose/results directory)

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-frontend/blob/master/tools/update.py#L276
```sql
INSERT INTO marker (source, class, subclass, item, lat, lon, elems, subtitle) VALUES (" + "%s," * 7 + "%s) RETURNING id
```

```
Indexes:
    "marker_pkey" PRIMARY KEY, btree (id) CLUSTER, tablespace "ssd"
    "idx_marker_item" btree (item), tablespace "ssd"
    "idx_marker_lat_lon" btree (lat, lon)
    "idx_marker_source_class" btree (source, class), tablespace "ssd"
    "idx_marker_source_class_subclass_lat_lon_elems" btree (source, class, subclass, lat, lon, elems), tablespace "ssd"
    "marker_geom" gist (point(lat::double precision, lon::double precision)), tablespace "ssd"
```
The only size vairable index is `idx_marker_source_class_subclass_lat_lon_elems`.
item=1230 class=5 can send variable number of element. I think there is hundreds of nodes duplicated in some place.

**Comment by frodrigo** [comment]
The 3478 duplicate nodes are already deleted http://www.openstreetmap.org/changeset/49906749
