### ISSUE TITLE
src_state in sax analyse

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#234]
since last update i've this error

> 
2017-09-27 17:01:14   DROP SCHEMA russia_ulyanovsk_oblast
2017-09-27 17:01:14 [0;31mimport osmosis schema[0m
2017-09-27 17:01:16 [0;31mimport osmosis data[0m
2017-09-27 17:06:57 [0;31mimport osmosis post scripts[0m
2017-09-27 17:09:34 [0;31mrename osmosis tables[0m
2017-09-27 17:09:34 [0;31mimport post scripts[0m
2017-09-27 17:09:35 [0;31mrussia_ulyanovsk_oblast : sax[0m
2017-09-27 17:09:36   error on analyse...
2017-09-27 17:09:36     Traceback (most recent call last):
2017-09-27 17:09:36       File "./osmose_run.py", line 677, in run
2017-09-27 17:09:36         with obj(analyser_conf, logger.sub()) as analyser_obj:
2017-09-27 17:09:36       File "./analysers/analyser_sax.py", line 40, in __enter__
2017-09-27 17:09:36         self._load_parser()
2017-09-27 17:09:36       File "./analysers/analyser_sax.py", line 342, in _load_parser
2017-09-27 17:09:36         self.parser = OsmPbfReader(self.config.src, self.config.src_state, self.logger.sub())
2017-09-27 17:09:36     AttributeError: analyser_config instance has no attribute 'src_state'
2017-09-27 17:09:36     

>

**Comment by jocelynj** [comment]
@frodrigo told me that he has a fix for this issue, that we see on any country that doesn't have any state.txt file available.
It is due to a recent change to use timestamp from state.txt to calculate the date/time of analysis run. Of state.txt is not available, it should take timestamp from pbf, but this is a bit broken.

**Comment by frodrigo** [comment]
5c2cf362b6e1c7516a2a9e3579acae13ac0e27ec

**Comment by jocelynj** [comment]
Pushed to master, thanks.
