### ISSUE TITLE
analyser_merge_shop_FR fails downloading Sirene data

### ISSUE THREAD

**Issue by jccomputing** [osm-fr/osmose-backend#2346]
For about one week, the `merge_shop_FR` analyzer is failing because it can't dowload data. For example:

https://buildbot.osmose.openstreetmap.fr/#/builders/528/builds/1443

```console
2024-10-01 03:11:36 france_alsace_bas_rhin : merge_shop_FR
2024-10-01 03:11:39   error: error on analyse merge_shop_FR...
2024-10-01 03:11:39     Traceback (most recent call last):
2024-10-01 03:11:39       File "/data/project/osmose/backend/./osmose_run.py", line 259, in execc
2024-10-01 03:11:39         if analyser_obj.timestamp() and remote_timestamp and analyser_obj.timestamp() <= remote_timestamp and analyser_obj.analyser_version() == remote_analyser_version:
2024-10-01 03:11:39            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge_Dynamic.py", line 51, in timestamp
2024-10-01 03:11:39         with self.analysers[0](self.config, self.error_file,  self.logger) as analyser_obj:
2024-10-01 03:11:39              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge_Dynamic.py", line 32, in __init__
2024-10-01 03:11:39         classs.__init__(self, config, error_file, logger, *args)
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/analyser_merge_shop_FR.py", line 56, in __init__
2024-10-01 03:11:39         self.init(
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge_Dynamic.py", line 67, in init
2024-10-01 03:11:39         Analyser_Merge_Point.init(self, url, name, source, load, mapping)
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1414, in init
2024-10-01 03:11:39         super().init(url, name, parser, load, conflate)
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1255, in init
2024-10-01 03:11:39         self.conflate.mapping.eval_static(self)
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1165, in eval_static
2024-10-01 03:11:39         self.eval_staticGroup(self.static2, analyser)
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1159, in eval_staticGroup
2024-10-01 03:11:39         r = colomn()
2024-10-01 03:11:39             ^^^^^^^^
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 1270, in source
2024-10-01 03:11:39         return self.parser.source.as_tag_value()
2024-10-01 03:11:39                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 454, in as_tag_value
2024-10-01 03:11:39         return " - ".join(filter(lambda x: x is not None, [self.attribution, self._get_millesime()]))
2024-10-01 03:11:39                                                                              ^^^^^^^^^^^^^^^^^^^^^
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 440, in _get_millesime
2024-10-01 03:11:39         self.millesime = self.get_millesime()
2024-10-01 03:11:39                          ^^^^^^^^^^^^^^^^^^^^
2024-10-01 03:11:39       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 532, in get_millesime
2024-10-01 03:11:39         downloader.requests_retry_session().head(self.fileUrl).headers['Last-Modified'],
2024-10-01 03:11:39         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
2024-10-01 03:11:39       File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
2024-10-01 03:11:39         return self._store[key.lower()][1]
2024-10-01 03:11:39                ~~~~~~~~~~~^^^^^^^^^^^^^
2024-10-01 03:11:39     KeyError: 'last-modified'
```

As seen [here](https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_merge_shop_FR.py#L62), it tries to access file on @cquest server but the `last` directory is not there anymore.

I don't know what's the proper fix to this problem and if the fix has to be on the source server or if osmose-backend code has to be adapted.

**Comment by merylstreet** [comment]
This analyser should be disabled and/or item=8310 should be removed from osmose frontend.

Currently it's proposing to add SIRETs that have been closed for more than a year:

https://osmose.openstreetmap.fr/fr/map/#item=8310&level=1%2C2%2C3&loc=19/49.1784366/-0.3560656&issue_uuid=d4548ffb-9942-ef90-66ae-1a58f95b58f1

https://annuaire-entreprises.data.gouv.fr/etablissement/90833967400016

**Comment by frodrigo** [comment]
The configurerd datasource is no more available. It has to be switched to the official INSEE source.

**Comment by merylstreet** [comment]
I'm not sure I have the technical level but I can try and help.

As far as I am aware, the INSEE source is for the whole of France and not per department as used to be the case at data.cquest.org.

So we would need to either pre-process the INSEE source to break it down into department CSVs or do this on the fly? 
Is the second option doable or would it be too heavy to run?

**Comment by frodrigo** [comment]
New data is available here https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/ in "Sirene : Fichier StockEtablissement du 01 Avril 2025"

**Comment by merylstreet** [comment]
Alright I spent quite a lot of time fiddling with this but in the end I can't even check if it works, the Sirene csv file is 9GB and it crashes my system (not enough RAM so Docker exists with 139)... so I kind of give up

**Comment by frodrigo** [comment]
* "Sirene : Fichier StockEtablissement du 01 Mai 2025" of 1.2GB is not the good one ?
* As the source level https://github.com/osm-fr/osmose-backend/blob/dev/doc/4-Merge.md#common-attributes you can use the `filter` to "hack" to content to reduce the size if required.

**Comment by merylstreet** [comment]
This is what I've been doing

The 1.2GB zip file is a 9GB csv file unzipped.

By filter, you mean using where, right?
This is what I was doing below but Docker runs out of RAM and kills the import process not long after printing "Load raw data into database"

`        self.init(
            "http://www.sirene.fr/sirene/public/static/open-data",
            "Sirene",
            CSV(SourceHttpLastModified(
                attribution="INSEE",
                zip='StockEtablissement_utf8.csv',
                fileUrl="https://files.data.gouv.fr/insee-sirene/StockEtablissement_utf8.zip"),
                srid=2154),
            Load_XY(
                "coordonneelambertabscisseetablissement", 
                "coordonneelambertordonneeetablissement",
                select={"activitePrincipaleEtablissement": classs, "etatAdministratifEtablissement": "A"},
                where=lambda res: (
                    res["codeCommuneEtablissement"].startswith("06") and
                    (not res["complementAdresseEtablissement"] or (" APP" not in res["complementAdresseEtablissement"] and " CHEZ " not in res["complementAdresseEtablissement"])) and
                    (not trancheEffectifs or (res["trancheEffectifsEtablissement"] and res["trancheEffectifsEtablissement"] != "NN" and int(res["trancheEffectifsEtablissement"]) > trancheEffectifs))
                ),
                unique=["siren", "nic"]
            ),`

**Comment by frodrigo** [comment]
No, using the filter lambda or functions at reading steps, before loading.

**Comment by cquest** [comment]
Replacement data source for the one I'm not generating anymore : https://www.data.gouv.fr/datasets/base-sirene-des-etablissements-siret-geolocalisee-avec-la-base-dadresse-nationale-ban

It should be very similar in its structure as they reused and adapted my scripts.
