### ISSUE TITLE
InternalError: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#287]
Indonesia analysis fails since a few days. Might be a problem with OSM data, but a quality check tool should then report a problem and not fail itself.

```
2018-04-02 04:37:13 indonesia : osmosis_building_overlaps
2018-04-02 04:37:14   run osmosis all analyser Analyser_Osmosis_Building_Overlaps
2018-04-02 04:37:14   requires table buildings
2018-04-02 04:44:06   analyser_osmosis_building_overlaps.py:175 sql
2018-04-02 04:45:03   analyser_osmosis_building_overlaps.py:176 sql
2018-04-02 04:56:47   analyser_osmosis_building_overlaps.py:177 sql
2018-04-02 05:15:01   sql=
CREATE TABLE intersection__ AS
SELECT
    b1.id AS id1,
    b2.id AS id2,
    ST_AsText(ST_Transform(ST_Centroid(ST_Intersection(b1.polygon_proj, b2.polygon_proj)), 4326)),
    ST_Area(ST_Intersection(b1.polygon_proj, b2.polygon_proj)) AS intersectionArea,
    least(b1.area, b2.area) * 0.10 AS threshold,
    b1.polygon_proj
FROM
    buildings AS b1
    JOIN buildings AS b2 ON
        b1.id > b2.id AND
        b1.linestring && b2.linestring AND
        ST_Area(ST_Intersection(b1.polygon_proj, b2.polygon_proj)) > 0
WHERE
    b1.wall AND
    b2.wall AND
    NOT b1.relation AND
    NOT b2.relation AND
    NOT b1.layer AND
    NOT b2.layer AND
    b1.polygon_proj IS NOT NULL AND
    b2.polygon_proj IS NOT NULL


2018-04-02 05:15:01   error on analyse...
2018-04-02 05:15:01     Traceback (most recent call last):
2018-04-02 05:15:01       File "./osmose_run.py", line 233, in run
2018-04-02 05:15:01         analyser_obj.analyser()
2018-04-02 05:15:01       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 173, in analyser
2018-04-02 05:15:01         self.analyser_osmosis_full()
2018-04-02 05:15:01       File "/opt/osmose-backend/analysers/analyser_osmosis_building_overlaps.py", line 177, in analyser_osmosis_full
2018-04-02 05:15:01         self.run(sql30.format("", ""))
2018-04-02 05:15:01       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 428, in run
2018-04-02 05:15:01         self.run0(sql)
2018-04-02 05:15:01       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 382, in run0
2018-04-02 05:15:01         self.giscurs.execute(sql)
2018-04-02 05:15:01       File "/usr/lib/python2.7/dist-packages/psycopg2/extras.py", line 120, in execute
2018-04-02 05:15:01         return super(DictCursor, self).execute(query, vars)
2018-04-02 05:15:01     InternalError: Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -357637.03082210512 723004.93429539574 at -357637.03082210512 723004.93429539574
```

**Comment by jocelynj** [comment]
Thanks for reporting the issue.

This should be linked to a way or relation with an incorrect geometry, which is detected by another analysis. The best way to handle this error is to directly fix the error on OSM database, but I cannot find an easy way to find the erroneous way :(

Note that we have the same issue in south-africa.

**Comment by jocelynj** [comment]
@frodrigo and I have fixed the geometry issues reported by osmose on the coordinate reported. This should fix this ticket.

**Comment by stephankn** [comment]
I don't think that invalid geometry should be able to crash Osmose. Having invalid geometry is not nice to have, but a valid case as not enforced by the OSM API.
So Osmose should be robust against this kind of problems. 
How about catching the return code and ignoring invalid geometry problems, as these are detected by another analyzer?

**Comment by stephankn** [comment]
So you say it's this st_area/st_intersection which later creates an invalid geometry?
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_building_overlaps.py#L50

so would it help to add a where clause ST_IsValid(...)? Then it would not match invalid geometries and not trying to return it?

**Comment by frodrigo** [comment]
Yes we can fix the code in this way.
