### ISSUE TITLE
Characters '-' in the name of an analyser trigger an error in the frontend

### ISSUE THREAD

**Issue by allier-osm** [osm-fr/osmose-backend#389]
It seems that the presence of characters '-' in the name of the analyzer ```analyser_osmosis_highway_cul-de-sac_level.py``` triggers an error when the frontend tries to split the analyser-country string sent by the backend.

```
backend_1_x | 2018-11-10 14:06:11   run osmosis all analyser Analyser_Osmosis_Highway_CulDeSac_Level
backend_1_x | 2018-11-10 14:06:11   requires table highway_ends
backend_1_x | 2018-11-10 14:06:11   requires table highways
backend_1_x | 2018-11-10 14:06:12   analyser_osmosis_highway_cul-de-sac_level.py:68 xml generation
backend_1_x | 2018-11-10 14:06:12   update
backend_1_x | 2018-11-10 14:06:12     iteration=1
frontend_1_y | Traceback (most recent call last):
frontend_1_y |   File "/data/project/osmose/frontend/osmose-frontend-venv/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
frontend_1_y |     return route.call(**args)
frontend_1_y |   File "/data/project/osmose/frontend/osmose-frontend-venv/local/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
frontend_1_y |     rv = callback(*a, **ka)
frontend_1_y |   File "/data/project/osmose/frontend/bottle_pgsql.py", line 107, in wrapper
frontend_1_y |     rv = callback(*args, **kwargs)
frontend_1_y |   File "/data/project/osmose/frontend/bottle_cors.py", line 32, in wrapper
frontend_1_y |     return callback(*args, **kwargs)
frontend_1_y |   File "/data/project/osmose/frontend/control.py", line 259, in send_update
frontend_1_y |     analyser, country = src.split("-")
frontend_1_y | ValueError: too many values to unpack
```

**Comment by frodrigo** [comment]
You point an issue, but your conclusion is not right. This analyser and all the others are already heavy in use.

**Comment by allier-osm** [comment]
You are right that this does not happen in production mode. The code path that triggers this issue is activated only in development mode (OSMOSE_UNLOCKED_UPDATE=on).
