### ISSUE TITLE
analysis hangs forever, PBFParserProcess fails

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#401]
Version: commit c071c51c4415dd49bcbcb2e2e03492d864eaf824

backend running in container hangs forever. docker logs shows the below output as the last signs.

why is osmose_run.py not detecting the fault and terminating?

Another question would be why the parser fail/the extract is broken, but maybe this is a different topic.
I will recover a copy of one of the failing extracts for a closer look.

```
2018-11-20 03:21:01   Analysing file /data/work/osmose/extracts/singapore.osm.pbf                                                                                          
Process PBFParserProcess-1:2:                                                                                                                                              
Traceback (most recent call last):                                                                                                                                         
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap                                                                                            
    self.run()                                                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/imposm/parser/pbf/multiproc.py", line 36, in run                                                                            
    size=pos['blob_size'])                                                                                                                                                 
  File "/usr/local/lib/python2.7/dist-packages/imposm/parser/pbf/parser.py", line 69, in parse                                                                             
    reader = PrimitiveBlockParser(filename, offset, size)                                                                                                                  
  File "/usr/local/lib/python2.7/dist-packages/imposm/parser/pbf/parser.py", line 156, in __init__                                                                         
    data = read_blob_data(filename, blob_pos, blob_size)                                                                                                                   
  File "/usr/local/lib/python2.7/dist-packages/imposm/parser/pbf/parser.py", line 293, in read_blob_data                                                                   
    return zlib.decompress(blob.zlib_data)                                                                                                                                 
error: Error -5 while decompressing data: incomplete or truncated stream                                                                                                   
```

**Comment by frodrigo** [comment]
We are facing the same issue.
Is not linked to this commit nor docker.
There is trouble to download extract from download.openstreetmap.fr
cc @marc-marc-marc

**Comment by stephankn** [comment]
Just stated the HEAD hash to be specific in which version I observed it.

Thanks for confirming a data problem, but still: why does it hang and not exit with a nice error message? 

This would now require to implement an external watchdog to kill the processing after a timeout.

**Comment by frodrigo** [comment]
We still don't know. But I have I fix to stop this at the download step. We will release it shortly.

**Comment by frodrigo** [comment]
We release the change and it do the job. It stop the process before parsing the pbf file fore ever.
