### ISSUE TITLE
france_saintmartin : merge_college_FR : error 404

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-backend#407]
http://buildbot.osmose.openstreetmap.fr/builders/france_saintmartin/builds/386/steps/osmose_run.py/logs/stdio
2018-11-23 02:33:11 france_saintmartin : merge_college_FR
2018-11-23 02:33:11   run osmosis all analyser Analyser_Merge_College_FR
2018-11-23 02:33:11   error on analyse...
2018-11-23 02:33:11     Traceback (most recent call last):
2018-11-23 02:33:11       File "./osmose_run.py", line 251, in run
2018-11-23 02:33:11         analyser_obj.analyser()
2018-11-23 02:33:11       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 173, in analyser
2018-11-23 02:33:11         self.error_file.analyser(self.apiconn.timestamp(), self.analyser_version())
2018-11-23 02:33:11       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 843, in analyser_version
2018-11-23 02:33:11         return SourceVersion.version(self.parser.source.time(), self.__class__)
2018-11-23 02:33:11       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 329, in time
2018-11-23 02:33:11         return int(downloader.urlmtime(self.fileUrl, self.fileUrlCache)+.5)
2018-11-23 02:33:11       File "/data/project/osmose/backend/analysers/modules/downloader.py", line 104, in urlmtime
2018-11-23 02:33:11         return os.stat(update_cache(url, delay)).st_mtime
2018-11-23 02:33:11       File "/data/project/osmose/backend/analysers/modules/downloader.py", line 64, in update_cache
2018-11-23 02:33:11         answer = urllib_urlopen(request)
2018-11-23 02:33:11       File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
2018-11-23 02:33:11         return opener.open(url, data, timeout)
2018-11-23 02:33:11       File "/usr/lib/python2.7/urllib2.py", line 435, in open
2018-11-23 02:33:11         response = meth(req, response)
2018-11-23 02:33:11       File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
2018-11-23 02:33:11         'http', request, response, code, msg, hdrs)
2018-11-23 02:33:11       File "/usr/lib/python2.7/urllib2.py", line 473, in error
2018-11-23 02:33:11         return self._call_chain(*args)
2018-11-23 02:33:11       File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
2018-11-23 02:33:11         result = func(*args)
2018-11-23 02:33:11       File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
2018-11-23 02:33:11         raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
2018-11-23 02:33:11     HTTPError: HTTP Error 404: Not Found
maybe related to #299

**Comment by frodrigo** [comment]
cc @deuzeffe

**Comment by frodrigo** [comment]
There is only one file for all part of France. Same error for other areas.
The is online. I think it's a temporary failure.
