### ISSUE TITLE
Analyzers failing, AttributeError: 'NoneType' object has no attribute 'replace' 

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#408]
Analyzers are failing.  I don't know why, but self.config.version seems to exist but is None. 

```
2018-11-23 00:49:59 thailand : osmosis_roundabout_reverse
2018-11-23 00:50:00   run osmosis all analyser Analyser_Osmosis_Roundabout_Reverse                                                                                             
2018-11-23 00:50:00   error on analyse...                                                                                                                                      
2018-11-23 00:50:00     Traceback (most recent call last):                                                                                                                     
2018-11-23 00:50:00       File "./osmose_run.py", line 251, in run                                                                                                             
2018-11-23 00:50:00         analyser_obj.analyser()                                                                                                                            
2018-11-23 00:50:00       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 173, in analyser                                                                      
2018-11-23 00:50:00         self.error_file.analyser(self.apiconn.timestamp(), self.analyser_version())                                                                        
2018-11-23 00:50:00       File "/opt/osmose-backend/analysers/modules/OsmoseErrorFile.py", line 62, in analyser                                                                
2018-11-23 00:50:00         self.outxml.startElement(self.mode, attrs)                                                                                                         
2018-11-23 00:50:00       File "/opt/osmose-backend/analysers/modules/OsmSax.py", line 325, in startElement                                                                    
2018-11-23 00:50:00         self._write(u' %s=%s' % (name, quoteattr(value)))                                                                                                  
2018-11-23 00:50:00       File "/usr/lib/python2.7/xml/sax/saxutils.py", line 66, in quoteattr                                                                                 
2018-11-23 00:50:00         data = escape(data, entities)                                                                                                                      
2018-11-23 00:50:00       File "/usr/lib/python2.7/xml/sax/saxutils.py", line 32, in escape                                                                                    
2018-11-23 00:50:00         data = data.replace("&", "&amp;")                                                                                                                  
2018-11-23 00:50:00     AttributeError: 'NoneType' object has no attribute 'replace'                                                                                           
```

**Comment by stephankn** [comment]
Was caused by a nasty typo in modified get_version. This caused an exception which then set version = None.

latest change in #406 fixes typo and removes that broken exception handling. Alternative, if you want to keep the try/except, then version should be a string, not None.
