### ISSUE TITLE
Exception: No script setup for language 'lo'

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#423]
version: c2f7390e69384317ba2940660309a99d4f0c264b

I suppose something needs to be added to languages.py

maybe
`'lo': ['Lao'],
`

```
2018-12-19 00:49:18   error: error on analyse...
2018-12-19 00:49:18     Traceback (most recent call last):                                                                                                             
2018-12-19 00:49:18       File "./osmose_run.py", line 243, in execc                                                                                                   
2018-12-19 00:49:18         analyser_obj.analyser()                                                                                                                    
2018-12-19 00:49:18       File "/opt/osmose-backend/analysers/analyser_sax.py", line 53, in analyser                                                                   
2018-12-19 00:49:18         self._load_plugins()                                                                                                                       
2018-12-19 00:49:18       File "/opt/osmose-backend/analysers/analyser_sax.py", line 449, in _load_plugins                                                             
2018-12-19 00:49:18         if pluginInstance.init(self.logger.sub().sub()) == False:                                                                                  
2018-12-19 00:49:18       File "/opt/osmose-backend/plugins/Name_Script.py", line 72, in init                                                                          
2018-12-19 00:49:18         raise Exception("No script setup for language '%s'" % language)                                                                            
2018-12-19 00:49:18     Exception: No script setup for language 'lo'                                                                                                   

```

**Comment by frodrigo** [comment]
I recheck and there is missing more.
40e7259c4051c7ca62373aecd5fe7ed08fdd9563
