### ISSUE TITLE
GrammarError: Rules defined twice: <__anon_star_4 : __anon_star_4 __IGNORE_0 timespan>, <__anon_star_4 : __IGNORE_0 timespan>

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#438]
Global issue.

v1.1-2019-01-06-38-g4a8eac3

```
2019-01-23 00:52:23     Traceback (most recent call last):
2019-01-23 00:52:23       File "./osmose_run.py", line 228, in execc
2019-01-23 00:52:23         analyser_obj.analyser()
2019-01-23 00:52:23       File "/opt/osmose-backend/analysers/analyser_sax.py", line 56, in analyser
2019-01-23 00:52:23         self._load_plugins()
2019-01-23 00:52:23       File "/opt/osmose-backend/analysers/analyser_sax.py", line 437, in _load_plugins
2019-01-23 00:52:23         pluginModule = importlib.import_module("plugins."+pluginName)
2019-01-23 00:52:23       File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
2019-01-23 00:52:23         __import__(name)
2019-01-23 00:52:23       File "/opt/osmose-backend/plugins/TagFix_Opening_Hours.py", line 24, in <module>
2019-01-23 00:52:23         from modules.oh_sanitizer import sanitize_field, SanitizeError, InconsistentField
2019-01-23 00:52:23       File "/opt/osmose-backend/modules/oh_sanitizer/__init__.py", line 26, in <module>
2019-01-23 00:52:23         from .main import sanitize_field, SanitizeError, InconsistentField
2019-01-23 00:52:23       File "/opt/osmose-backend/modules/oh_sanitizer/main.py", line 25, in <module>
2019-01-23 00:52:23         PARSER = get_parser()
2019-01-23 00:52:23       File "/opt/osmose-backend/modules/oh_sanitizer/main.py", line 22, in get_parser
2019-01-23 00:52:23         return _lark.Lark(grammar, start="time_domain", parser="earley")
2019-01-23 00:52:23       File "/usr/local/lib/python2.7/dist-packages/lark/lark.py", line 169, in __init__
2019-01-23 00:52:23         self.parser = self._build_parser()
2019-01-23 00:52:23       File "/usr/local/lib/python2.7/dist-packages/lark/lark.py", line 193, in _build_parser
2019-01-23 00:52:23         return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
2019-01-23 00:52:23       File "/usr/local/lib/python2.7/dist-packages/lark/parser_frontends.py", line 99, in __init__
2019-01-23 00:52:23         **kw
2019-01-23 00:52:23       File "/usr/local/lib/python2.7/dist-packages/lark/parsers/xearley.py", line 34, in __init__
2019-01-23 00:52:23         self.analysis = GrammarAnalyzer(parser_conf)
2019-01-23 00:52:23       File "/usr/local/lib/python2.7/dist-packages/lark/parsers/grammar_analysis.py", line 117, in __init__
2019-01-23 00:52:23         raise GrammarError("Rules defined twice: %s" % ', '.join(str(i) for i in duplicates))
2019-01-23 00:52:23     GrammarError: Rules defined twice: <__anon_star_4 : __anon_star_4 __IGNORE_0 timespan>, <__anon_star_4 : __IGNORE_0 timespan>
```

**Comment by stephankn** [comment]
I quickly browsed commit history. This one changed something nearby, but is not directly showing up in traceback:
https://github.com/osm-fr/osmose-backend/commit/4716e70149b303219fb2578913c8bab859d20844

**Comment by frodrigo** [comment]
More probably issued by this change: https://github.com/osm-fr/osmose-backend/commit/924670de8a654bc08c61d2e439cded52c1c616a9

**Comment by frodrigo** [comment]
I have same issue. It's happen only with docker setup.
cc @rezemika

**Comment by rezemika** [comment]
Thank you for the ping! I just uploaded a `v0.1.10` version of `oh_sanitizer`. :)
