### ISSUE TITLE
analyser_osmosis_way_approximate: DataError: integer out of range

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#440]
Version: v1.1-2019-01-06-73-g92f2cbc9

```
2019-02-04 07:26:11 china_shandong : osmosis_way_approximate
2019-02-04 07:26:13   run osmosis all analyser Analyser_Osmosis_Way_Approximate
2019-02-04 07:26:13   analyser_osmosis_way_approximate.py:129 sql
2019-02-04 07:26:13   analyser_osmosis_way_approximate.py:130 sql
2019-02-04 07:26:13   analyser_osmosis_way_approximate.py:132 xml generation
2019-02-04 07:26:16   analyser_osmosis_way_approximate.py:132 xml generation
2019-02-04 07:26:25   analyser_osmosis_way_approximate.py:132 xml generation
2019-02-04 07:26:29   error: sql=
SELECT
    id,
    ST_AsText(ST_PointN(_linestring, index)),
    (GREATEST(
        discard3points(
            ST_PointN(linestring, index-1),
            ST_PointN(linestring, index),
            ST_PointN(linestring, index+1)
        ),
        discard3points(
            ST_PointN(linestring, index+1),
            ST_PointN(linestring, index),
            ST_PointN(linestring, index-1)
        )
    )/2)::int AS d,
    type,
    30
FROM (
    SELECT
        id,
        linestring AS _linestring,
        ST_Transform(linestring, 32650) AS linestring,
        generate_series(2, ST_NPoints(linestring)-1) AS index,
        tags->'highway' AS type
    FROM
        ways AS ways
    WHERE
        tags != ''::hstore AND
        tags?'highway' AND tags->'highway' IN ('motorway', 'trunk', 'primary', 'secondary') AND
        ST_NPoints(linestring) >= 4
) AS foo
WHERE
    GREATEST(
        discard3points(
            ST_PointN(linestring, index-1),
            ST_PointN(linestring, index),
            ST_PointN(linestring, index+1)
        ),
        discard3points(
            ST_PointN(linestring, index+1),
            ST_PointN(linestring, index),
            ST_PointN(linestring, index-1)
        )
    ) > 70

2019-02-04 07:26:29   error: error on analyse...
2019-02-04 07:26:29     Traceback (most recent call last):
2019-02-04 07:26:29       File "./osmose_run.py", line 228, in execc
2019-02-04 07:26:29         analyser_obj.analyser()
2019-02-04 07:26:29       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 184, in analyser
2019-02-04 07:26:29         self.analyser_osmosis_full()
2019-02-04 07:26:29       File "/opt/osmose-backend/analysers/analyser_osmosis_way_approximate.py", line 132, in analyser_osmosis_full
2019-02-04 07:26:29         self.run(sql12.format("", t[1], "', '".join(t[2]), t[0], self.config.options.get("proj")), self.callback10)
2019-02-04 07:26:29       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 441, in run
2019-02-04 07:26:29         self.run0(sql, callback_package)
2019-02-04 07:26:29       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 398, in run0
2019-02-04 07:26:29         self.giscurs.execute(sql)
2019-02-04 07:26:29       File "/usr/local/lib/python2.7/site-packages/psycopg2/extras.py", line 141, in execute
2019-02-04 07:26:29         return super(DictCursor, self).execute(query, vars)
2019-02-04 07:26:29     DataError: integer out of range
2
```

**Comment by frodrigo** [comment]
Way 243137378 at POINT(116.5393804 35.2835878) return a NaN that doesn't support the cast to int.
Reproduced on docker. Not on plain install.
