### ISSUE TITLE
ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#452]
v1.1-2019-02-16-40-g721f9d76

multiple countries affected by SQL error:

```
2019-02-20 06:10:44 china_fujian : osmosis_powerline
2019-02-20 06:10:45   run osmosis all analyser Analyser_Osmosis_Powerline
2019-02-20 06:10:45   analyser_osmosis_powerline.py:322 xml generation
2019-02-20 06:10:45   error: sql=
SELECT
    nodes.id,
    ST_AsText(nodes.geom)
FROM
    nodes
    LEFT JOIN way_nodes ON
        way_nodes.node_id = nodes.id
    LEFT JOIN ways ON
        ways.id = way_nodes.way_id AND
        ways.tags != ''::hstore AND
        ways.tags?'power' AND
        ways.tags->'power' IN ('line', 'minor_line', 'cable')
WHERE
    nodes.tags != ''::hstore AND
    nodes.tags?'power' AND
    nodes.tags->'power' IN ('pole', 'tower')
GROUP BY
    nodes.id
HAVING
    bool_and(ways.id IS NULL)

2019-02-20 06:10:45   error: error on analyse osmosis_powerline...
2019-02-20 06:10:45     Traceback (most recent call last):
2019-02-20 06:10:45       File "./osmose_run.py", line 229, in execc
2019-02-20 06:10:45         analyser_obj.analyser()
2019-02-20 06:10:45       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 183, in analyser
2019-02-20 06:10:45         self.analyser_osmosis_common()
2019-02-20 06:10:45       File "/opt/osmose-backend/analysers/analyser_osmosis_powerline.py", line 322, in analyser_osmosis_common
2019-02-20 06:10:45         self.run(sql10, lambda res: {"class":1, "data":[self.node_full, self.positionAsText]} )
2019-02-20 06:10:45       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 441, in run
2019-02-20 06:10:45         self.run0(sql, callback_package)
2019-02-20 06:10:45       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 398, in run0
2019-02-20 06:10:45         self.giscurs.execute(sql)
2019-02-20 06:10:45       File "/usr/local/lib/python2.7/site-packages/psycopg2/extras.py", line 141, in execute
2019-02-20 06:10:45         return super(DictCursor, self).execute(query, vars)
2019-02-20 06:10:45     ProgrammingError: column "nodes.geom" must appear in the GROUP BY clause or be used in an aggregate function
2019-02-20 06:10:45     LINE 4:     ST_AsText(nodes.geom)
2019-02-20 06:10:45                           ^
2019-02-20 06:10:45
```

**Comment by frodrigo** [comment]
We do not make changes on SQL recently. It look like the code running on a other postgres version.

**Comment by frodrigo** [comment]
I rebuild a docker image without cache and I don't see any issue.

**Comment by frodrigo** [comment]
Ok, I got the same issue.
