### ISSUE TITLE
ProgrammingError: function way_locate(geometry) does not exist

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#454]
v1.1-2019-02-16-40-g721f9d76

```
2019-02-20 05:03:49 china_gansu : merge_traffic_signs
2019-02-20 05:03:55   Retrive OSM item
2019-02-20 05:03:55   Analyser_Merge.py:866 sql
2019-02-20 05:03:55   error: sql=CREATE TEMP TABLE osm_item AS (
                    SELECT
                        'W'::char(1) AS type,
                        id,
                        trim(both from ref) AS ref,
                        way_locate(linestring)::geography AS geom,
                        ST_Envelope(linestring)::geography AS shape,
                        tags
                    FROM
                        ways
                        LEFT JOIN LATERAL regexp_split_to_table(tags->'NULL', ';') a(ref) ON true
                    WHERE
                        linestring IS NOT NULL AND
                        ST_SetSRID(ST_GeomFromText('POLYGON((102.844010049 37.4383155045,102.844010049 37.4913000994,102.896804256 37.4913000994,102.896804256 37.4383155045,102.844010049 37.4383155045))'), 4326) && linestring AND
                        tags != ''::hstore AND
                        (tags?'maxspeed' AND tags->'maxspeed' = '5' AND tags?'highway'))
2019-02-20 05:03:55   error: error on analyse merge_traffic_signs...
2019-02-20 05:03:55     Traceback (most recent call last):
2019-02-20 05:03:55       File "./osmose_run.py", line 229, in execc
2019-02-20 05:03:55         analyser_obj.analyser()
2019-02-20 05:03:55       File "/opt/osmose-backend/analysers/Analyser_Merge_Dynamic.py", line 44, in analyser
2019-02-20 05:03:55         analyser_obj.analyser()
2019-02-20 05:03:55       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 183, in analyser
2019-02-20 05:03:55         self.analyser_osmosis_common()
2019-02-20 05:03:55       File "/opt/osmose-backend/analysers/Analyser_Merge.py", line 866, in analyser_osmosis_common
2019-02-20 05:03:55         self.mapping.select.types
2019-02-20 05:03:55       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 444, in run
2019-02-20 05:03:55         self.run0(sql)
2019-02-20 05:03:55       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 398, in run0
2019-02-20 05:03:55         self.giscurs.execute(sql)
2019-02-20 05:03:55       File "/usr/local/lib/python2.7/site-packages/psycopg2/extras.py", line 141, in execute
2019-02-20 05:03:55         return super(DictCursor, self).execute(query, vars)
2019-02-20 05:03:55     ProgrammingError: function way_locate(geometry) does not exist
2019-02-20 05:03:55     LINE 6:                         way_locate(linestring)::geography AS...
2019-02-20 05:03:55                                     ^
2019-02-20 05:03:55     HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2019-02-20 05:03:55
```

**Comment by frodrigo** [comment]
I can't reproduce this one today.

**Comment by stephankn** [comment]
Duplicate of #453
