### ISSUE TITLE
ProgrammingError: function relation_locate(bigint) does not exist

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#455]
v1.1-2019-02-16-40-g721f9d76

multiple countries affected by SQL error:

```
2019-02-20 04:32:08 india_uttar_pradesh : osmosis_relation_associatedStreet
2019-02-20 04:32:08   run osmosis all analyser Analyser_Osmosis_Relation_AssociatedStreet
2019-02-20 04:32:08   analyser_osmosis_relation_associatedStreet.py:602 sql
2019-02-20 04:32:08   analyser_osmosis_relation_associatedStreet.py:603 sql
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:604 xml generation
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:605 xml generation
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:607 sql
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:608 sql
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:609 sql
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:610 xml generation
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:614 sql
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:615 xml generation
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:616 sql
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:617 sql
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:618 xml generation
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:619 xml generation
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:620 xml generation
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:621 xml generation
2019-02-20 04:32:09   analyser_osmosis_relation_associatedStreet.py:624 xml generation
2019-02-20 04:32:09   error: sql=
SELECT
    relations.id,
    ST_AsText(relation_locate(relations.id)) AS geom
FROM
    relations AS relations
    LEFT JOIN relation_members ON
        relations.id = relation_members.relation_id AND
        relation_members.member_type = 'W' AND
        relation_members.member_role = 'street'
WHERE
    relations.tags?'type' AND
    relations.tags->'type' = 'associatedStreet' AND
    relation_members.member_role IS NULL

2019-02-20 04:32:09   error: error on analyse osmosis_relation_associatedStreet...
2019-02-20 04:32:09     Traceback (most recent call last):
2019-02-20 04:32:09       File "./osmose_run.py", line 229, in execc
2019-02-20 04:32:09         analyser_obj.analyser()
2019-02-20 04:32:09       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 184, in analyser
2019-02-20 04:32:09         self.analyser_osmosis_full()
2019-02-20 04:32:09       File "/opt/osmose-backend/analysers/analyser_osmosis_relation_associatedStreet.py", line 624, in analyser_osmosis_full
2019-02-20 04:32:09         self.run(sql20.format(""), self.callback20)
2019-02-20 04:32:09       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 441, in run
2019-02-20 04:32:09         self.run0(sql, callback_package)
2019-02-20 04:32:09       File "/opt/osmose-backend/analysers/Analyser_Osmosis.py", line 398, in run0
2019-02-20 04:32:09         self.giscurs.execute(sql)
2019-02-20 04:32:09       File "/usr/local/lib/python2.7/site-packages/psycopg2/extras.py", line 141, in execute
2019-02-20 04:32:09         return super(DictCursor, self).execute(query, vars)
2019-02-20 04:32:09     ProgrammingError: function relation_locate(bigint) does not exist
2019-02-20 04:32:09     LINE 4:     ST_AsText(relation_locate(relations.id)) AS geom
2019-02-20 04:32:09                           ^
2019-02-20 04:32:09     HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2019-02-20 04:32:09
```

**Comment by frodrigo** [comment]
I can't reproduce this one today.

**Comment by stephankn** [comment]
Duplicate of #453
