### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#473]
osmose backend version: v1.1-2019-03-09-6-g0250c991
in Docker setup

multiple analyzers fail with a similar call stack. 
@jocelynj Can it be related to this recent change? https://github.com/osm-fr/osmose-backend/commit/ca6cd61e7e866ac14f29f1281331ae341e899306

```
[INFO] Reading the file/data/work/osmose/extracts/china_beijing.osm.pbf
2019-03-11 05:56:48   error: Error on error {'text': {'en': 'role="\xe6\xbb\x95\xe5\xb7\x9e"'}, 'class': 31700, 'subclass': 1} from [{'text': {'en': u'"alt_name:en"
="\u4eac\u6caa\u94c1\u8def" unexpected "\u4eac\u6caa\u94c1\u8def"'}, 'class': 50701, 'subclass': 1}, {'text': {'en': 'role="\xe6\xbb\x95\xe5\xb7\x9e"'}, 'class': 31
700, 'subclass': 1}]
2019-03-11 05:56:48   Closing reader and parser                                                                                                                     
2019-03-11 05:56:48   error: error on analyse sax...
2019-03-11 05:56:48     Traceback (most recent call last):                                                                                                          
2019-03-11 05:56:48       File "./osmose_run.py", line 230, in execc                                                                                                
2019-03-11 05:56:48         analyser_obj.analyser()                                                                                                                 
2019-03-11 05:56:48       File "/opt/osmose-backend/analysers/analyser_sax.py", line 60, in analyser                                                                
2019-03-11 05:56:48         self._run_analyse()                                                                                                                     
2019-03-11 05:56:48       File "/opt/osmose-backend/analysers/analyser_sax.py", line 498, in _run_analyse                                                           
2019-03-11 05:56:48         self.parser.CopyTo(self)                                                                                                                
2019-03-11 05:56:48       File "/opt/osmose-backend/analysers/modules/OsmPbf_libosmbf.py", line 78, in CopyTo                                                       
2019-03-11 05:56:48         osm_pbf_parser.read_osm_pbf(self._pbf_file, self)                                                                                       
2019-03-11 05:56:48       File "/opt/osmose-backend/analysers/modules/OsmPbf_libosmbf.py", line 113, in relation                                                    
2019-03-11 05:56:48         self._output.RelationCreate(data)                                                                                                       
2019-03-11 05:56:48       File "/opt/osmose-backend/analysers/analyser_sax.py", line 356, in RelationCreate                                                         
2019-03-11 05:56:48         {"position": [node], "relation": [data]})
2019-03-11 05:56:48       File "/opt/osmose-backend/analysers/modules/OsmoseErrorFile.py", line 91, in error
2019-03-11 05:56:48         self.outxml.Element("text", {"lang":lang, "value":text[lang]})
2019-03-11 05:56:48       File "/opt/osmose-backend/analysers/modules/OsmSax.py", line 326, in Element
2019-03-11 05:56:48         self._write(u' %s=%s' % (name, quoteattr(value)))
2019-03-11 05:56:48     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
```

another occurrence looks similar

```
[INFO] Reading the file/data/work/osmose/extracts/china_chongqing.osm.pbf
2019-03-11 05:57:52   error: Error on error {'text': {'en': 'role="\xe5\x9b\x9b\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\
xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81\x93"'}, 'class': 31700, 'subclass': 1} from [{'text': {'en': 'role="\xe5\x9b\x9b\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5
\xae\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81\x93"'}, 'class': 31700, 'subclass': 1}, {'text': {'en': 'role="\xe5\x9b\x9b
\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81\x93"'}, 'class': 31700, 'subclass':
 1}, {'text': {'en': 'role="\xe5\x9b\x9b\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9
\x81\x93"'}, 'class': 31700, 'subclass': 1}, {'text': {'en': 'role="\xe5\x9b\x9b\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3
\xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81\x93"'}, 'class': 31700, 'subclass': 1}, {'text': {'en': 'role="\xe5\x9b\x9b\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae
\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81\x93"'}, 'class': 31700, 'subclass': 1}, {'text': {'en': 'role="\xe5\x9b\x9b\xe5
\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81\x93"'}, 'class': 31700, 'subclass': 1},
 {'text': {'en': 'role="\xe5\x9b\x9b\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81
\x93"'}, 'class': 31700, 'subclass': 1}, {'text': {'en': 'role="\xe5\x9b\x9b\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae\xbe\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\xe5
\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81\x93"'}, 'class': 31700, 'subclass': 1}, {'text': {'en': 'role="\xe5\x9b\x9b\xe5\xb7\x9d\xe7\x9c\x81\xe5\xae\x9c\xe5\xae\xbe
\xe5\x8e\xbf\xe5\x88\xb0\xe8\x8d\xa3\xe5\x8e\xbf\xe4\xb8\xbb\xe5\xb9\xb2\xe9\x81\x93"'}, 'class': 31700, 'subclass': 1}]
2019-03-11 05:57:52   Closing reader and parser                                                                                                                     
2019-03-11 05:57:52   error: error on analyse sax...
2019-03-11 05:57:52     Traceback (most recent call last):                                                                                                          
2019-03-11 05:57:52       File "./osmose_run.py", line 230, in execc                                                                                                
2019-03-11 05:57:52         analyser_obj.analyser()
2019-03-11 05:57:52       File "/opt/osmose-backend/analysers/analyser_sax.py", line 60, in analyser
2019-03-11 05:57:52         self._run_analyse()
2019-03-11 05:57:52       File "/opt/osmose-backend/analysers/analyser_sax.py", line 498, in _run_analyse
2019-03-11 05:57:52         self.parser.CopyTo(self)
2019-03-11 05:57:52       File "/opt/osmose-backend/analysers/modules/OsmPbf_libosmbf.py", line 78, in CopyTo
2019-03-11 05:57:52         osm_pbf_parser.read_osm_pbf(self._pbf_file, self)
2019-03-11 05:57:52       File "/opt/osmose-backend/analysers/modules/OsmPbf_libosmbf.py", line 113, in relation
2019-03-11 05:57:52         self._output.RelationCreate(data)
2019-03-11 05:57:52       File "/opt/osmose-backend/analysers/analyser_sax.py", line 356, in RelationCreate
2019-03-11 05:57:52         {"position": [node], "relation": [data]})
2019-03-11 05:57:52       File "/opt/osmose-backend/analysers/modules/OsmoseErrorFile.py", line 91, in error
2019-03-11 05:57:52         self.outxml.Element("text", {"lang":lang, "value":text[lang]})
2019-03-11 05:57:52       File "/opt/osmose-backend/analysers/modules/OsmSax.py", line 326, in Element
2019-03-11 05:57:52         self._write(u' %s=%s' % (name, quoteattr(value)))
2019-03-11 05:57:52     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
```

list of analyzers in which it happens:
```
20190310_013701-thailand.log:2019-03-10 01:12:23     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 7: ordinal not in range(128)
20190310_030226-singapore.log:2019-03-10 02:07:13     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
20190310_031124-vietnam.log:2019-03-10 02:23:00     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 16: ordinal not in range(128)
20190310_033831-afghanistan.log:2019-03-10 02:43:19     UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 7: ordinal not in range(128)
20190310_062026-taiwan.log:2019-03-10 05:37:04     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 7: ordinal not in range(128)
20190310_064216-china_anhui.log:2019-03-10 05:44:29     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190310_064828-china_beijing.log:2019-03-10 05:50:53     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190310_065325-china_chongqing.log:2019-03-10 05:55:00     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_065339-china_fujian.log:2019-03-10 05:55:48     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 8: ordinal not in range(128)
20190310_065820-china_gansu.log:2019-03-10 06:01:45     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_065956-china_guangdong.log:2019-03-10 06:12:27     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)
20190310_070751-china_guangxi.log:2019-03-10 06:09:53     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190310_072533-china_hebei.log:2019-03-10 06:32:38     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190310_072925-china_heilongjiang.log:2019-03-10 06:31:49     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 9: ordinal not in range(128)
20190310_073542-china_henan.log:2019-03-10 06:37:58     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_074235-china_hong_kong.log:2019-03-10 06:46:39     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
20190310_074534-china_hubei.log:2019-03-10 06:47:50     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_075200-china_hunan.log:2019-03-10 06:54:58     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_075310-china_inner_mongolia.log:2019-03-10 06:56:26     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)
20190310_080056-china_jiangsu.log:2019-03-10 07:07:23     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190310_080414-china_jiangxi.log:2019-03-10 07:06:59     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_081728-china_liaoning.log:2019-03-10 07:19:35     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 7: ordinal not in range(128)
20190310_082320-china_qinghai.log:2019-03-10 07:24:52     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_082404-china_shaanxi.log:2019-03-10 07:26:26     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_082735-china_shandong.log:2019-03-10 07:31:40     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190310_082933-china_shanghai.log:2019-03-10 07:32:23     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190310_083922-china_sichuan.log:2019-03-10 07:44:37     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_084112-china_tianjin.log:2019-03-10 07:42:29     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190310_084428-china_tibet.log:2019-03-10 07:46:58     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_085327-china_yunnan.log:2019-03-10 07:56:45     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190310_090252-china_zhejiang.log:2019-03-10 08:07:47     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordinal not in range(128)
20190311_013702-thailand.log:2019-03-11 01:13:10     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 7: ordinal not in range(128)
20190311_030347-singapore.log:2019-03-11 02:08:30     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
20190311_031317-vietnam.log:2019-03-11 02:26:16     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 16: ordinal not in range(128)
20190311_033944-afghanistan.log:2019-03-11 02:44:46     UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 7: ordinal not in range(128)
20190311_062341-taiwan.log:2019-03-11 05:38:59     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 7: ordinal not in range(128)
20190311_064716-china_anhui.log:2019-03-11 05:49:30     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190311_065415-china_beijing.log:2019-03-11 05:56:48     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190311_065611-china_chongqing.log:2019-03-11 05:57:52     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_070022-china_fujian.log:2019-03-11 06:02:32     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 8: ordinal not in range(128)
20190311_070210-china_gansu.log:2019-03-11 06:05:20     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_070642-china_guangdong.log:2019-03-11 06:18:18     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)
20190311_071036-china_guangxi.log:2019-03-11 06:12:35     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190311_072833-china_hebei.log:2019-03-11 06:35:49     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190311_073906-china_heilongjiang.log:2019-03-11 06:41:20     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 9: ordinal not in range(128)
20190311_074535-china_henan.log:2019-03-11 06:47:43     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_074845-china_hong_kong.log:2019-03-11 06:52:19     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
20190311_075147-china_hubei.log:2019-03-11 06:53:58     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_075524-china_hunan.log:2019-03-11 06:58:53     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_075837-china_inner_mongolia.log:2019-03-11 07:02:02     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)
20190311_080429-china_jiangsu.log:2019-03-11 07:11:29     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190311_080950-china_jiangxi.log:2019-03-11 07:12:57     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_082352-china_liaoning.log:2019-03-11 07:26:07     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 7: ordinal not in range(128)
20190311_083008-china_qinghai.log:2019-03-11 07:31:57     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_083011-china_shaanxi.log:2019-03-11 07:32:37     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_083436-china_shandong.log:2019-03-11 07:38:31     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190311_083603-china_shanghai.log:2019-03-11 07:38:29     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190311_084559-china_sichuan.log:2019-03-11 07:50:46     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_084901-china_tianjin.log:2019-03-11 07:50:09     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 7: ordinal not in range(128)
20190311_085204-china_tibet.log:2019-03-11 07:54:14     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_085912-china_yunnan.log:2019-03-11 08:02:45     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
20190311_090916-china_zhejiang.log:2019-03-11 08:14:40     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordinal not in range(128)

**Comment by frodrigo** [comment]
Yes. We have the same issue. No fix yet.

**Comment by frodrigo** [comment]
Issue come from unicode char into role of relation by using the new osm pbf parser.

**Comment by frodrigo** [comment]
Merged.

**Comment by stephankn** [comment]
I can confirm that all previously failing analyzers recovered. Thanks for merging a fix.
