### ISSUE TITLE
ValueError: ("Dynamic Earley doesn't support weights on terminals", TerminalDef(u'EVENT', u'(?i)(?:(?i)(?:(?i)(?:(?i)dawn|(?i)sunrise)|(?i)sunset)|(?i)dusk)'), 2)

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#478]
osmose backend version: v1.1-2019-03-09-57-ge798b55f
running inside docker environment

I am not sure why this error just appeared today. Backend code should update quicker. But almost all (or all?) analyzers started failing today with the same error;

```
2019-03-31 00:39:28   error: error on analyse sax...
2019-03-31 00:39:28     Traceback (most recent call last):
2019-03-31 00:39:28       File "./osmose_run.py", line 230, in execc
2019-03-31 00:39:28         analyser_obj.analyser()
2019-03-31 00:39:28       File "/opt/osmose-backend/analysers/analyser_sax.py", line 57, in analyser
2019-03-31 00:39:28         self._load_plugins()
2019-03-31 00:39:28       File "/opt/osmose-backend/analysers/analyser_sax.py", line 440, in _load_plugins
2019-03-31 00:39:28         pluginModule = importlib.import_module("plugins."+pluginName)
2019-03-31 00:39:28       File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
2019-03-31 00:39:28         __import__(name)
2019-03-31 00:39:28       File "/opt/osmose-backend/plugins/TagFix_Opening_Hours.py", line 24, in <module>
2019-03-31 00:39:28         from modules.oh_sanitizer import sanitize_field, SanitizeError, InconsistentField
2019-03-31 00:39:28       File "/opt/osmose-backend/modules/oh_sanitizer/__init__.py", line 26, in <module>
2019-03-31 00:39:28         from .main import sanitize_field, SanitizeError, InconsistentField
2019-03-31 00:39:28       File "/opt/osmose-backend/modules/oh_sanitizer/main.py", line 25, in <module>
2019-03-31 00:39:28         PARSER = get_parser()
2019-03-31 00:39:28       File "/opt/osmose-backend/modules/oh_sanitizer/main.py", line 19, in get_parser
2019-03-31 00:39:28         return _lark.Lark(grammar, start="time_domain", parser="earley")
2019-03-31 00:39:28       File "/usr/local/lib/python2.7/site-packages/lark/lark.py", line 191, in __init__
2019-03-31 00:39:28         self.parser = self._build_parser()
2019-03-31 00:39:28       File "/usr/local/lib/python2.7/site-packages/lark/lark.py", line 215, in _build_parser
2019-03-31 00:39:28         return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
2019-03-31 00:39:28       File "/usr/local/lib/python2.7/site-packages/lark/parser_frontends.py", line 81, in __init__
2019-03-31 00:39:28         self._prepare_match(lexer_conf)
2019-03-31 00:39:28       File "/usr/local/lib/python2.7/site-packages/lark/parser_frontends.py", line 97, in _prepare_match
2019-03-31 00:39:28         raise ValueError("Dynamic Earley doesn't support weights on terminals", t, t.priority)
2019-03-31 00:39:28     ValueError: ("Dynamic Earley doesn't support weights on terminals", TerminalDef(u'EVENT', u'(?i)(?:(?i)(?:(?i)(?:(?i)dawn|(?i)sunrise)|(?i)sunset)|(?i)dusk)'), 2)
```

**Comment by frodrigo** [comment]
It's linked to the new release of the module lark parser.
