### ISSUE TITLE
MaxRetryError: HTTPSConnectionPool(host='a.mapillary.com', port=443): Max retries exceeded

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#505]
analyzer failed with a remote site not responding.

Should there be a better error handling/retry mechanism be implemented?

Is the 504 caused by some enforced rate-limiting of a load balancer of or simply the server not available?

```
2019-05-13 09:36:39   error: error on analyse merge_traffic_signs...
2019-05-13 09:36:39     Traceback (most recent call last):                                                                                                                
2019-05-13 09:36:39       File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send                                                           
2019-05-13 09:36:39         timeout=timeout                                                                                                                               
2019-05-13 09:36:39       File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen                                                   
2019-05-13 09:36:39         body_pos=body_pos, **response_kw)                                                                                                             
2019-05-13 09:36:39       File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen                                                   
2019-05-13 09:36:39         body_pos=body_pos, **response_kw)                                                                                                             
2019-05-13 09:36:39       File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 731, in urlopen                                                   
2019-05-13 09:36:39         body_pos=body_pos, **response_kw)                                                                                                             
2019-05-13 09:36:39       File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 711, in urlopen
2019-05-13 09:36:39         retries = retries.increment(method, url, response=response, _pool=self)
2019-05-13 09:36:39       File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 399, in increment
2019-05-13 09:36:39         raise MaxRetryError(_pool, url, error or ResponseError(cause))
2019-05-13 09:36:39     urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='a.mapillary.com', port=443): Max retries exceeded with url: /v3/map_features?bbox=97.528004,21.143139,106.1942062,29.2257206&client_id=XXXXXXX&layers=trafficsigns&per_page=1000&start_time=2017-05-13&values=regulatory--maximum-speed-limit-70--g1,regulatory--maximum-speed-limit-80--g1,regulatory--maximum-speed-limit-90--g1,regulatory--maximum-speed-limit-100--g1,regulatory--maximum-speed-limit-110--g1,regulatory--maximum-speed-limit-120--g1,regulatory--maximum-speed-limit-130--g1,regulatory--height-limit--g1,warning--height-restriction--g2,warning--height-restriction--g3 (Caused by ResponseError('too many 504 error responses',))
```

**Comment by frodrigo** [comment]
It may appear time by time. Depends on mapillary server load. Just ignore
it.
