### ISSUE TITLE
Create analysis on defibrillator

### ISSUE THREAD

**Issue by wadouk** [osm-fr/osmose-backend#596]
J'ai commencé une carte [mapcontrib](https://www.mapcontrib.xyz/t/7f46aa-Defibrillateur#) qui agrège les [différents jeux de données opendata](https://www.data.gouv.fr/fr/reuses/map-contrib-defibrillateurs-comparaison-osm-data-gouv-fr/) sur les défibrillateurs.

Je propose de regarder pour en faire une analyse.

OK ?
Des pointeurs de doc pour bien commencer le sujet ?

 - [x] [bas rhin](https://www.data.gouv.fr/fr/datasets/donnee-thematique-localisation-des-defibrillateurs-automatiques-externes-dae-bas-rhin/)
 - [x] [cugnaux](https://www.data.gouv.fr/fr/datasets/defibrillateurs-9/)
 - [x] [gers](https://www.data.gouv.fr/fr/datasets/inventaire-des-defibrillateurs-automatises-externes-dae-dans-le-gers/#)
 - [x] [hautes alpes](https://www.data.gouv.fr/fr/datasets/localisation-des-defibrillateurs-appartenant-au-departement-des-hautes-alpes/)
 - [x] [hautevienne](https://www.sigena.fr/geonetwork/srv/fre/catalog.search#/metadata/1e113a13-1865-43da-b027-d8abeafbf2dd)
 - [x] [issy les moulineaux](https://data.issy.com/explore/dataset/defibrillateurs-issy-les-moulineaux/information)
 - [x] [lorient](https://www.data.gouv.fr/fr/datasets/localisation-des-defibrillateurs-municipaux-dae-ville-de-lorient/)
 - [x] [montfort](https://www.data.gouv.fr/fr/datasets/defibrillateurs-montfort-communaute-1/)
 - [x] [paris](https://www.data.gouv.fr/fr/datasets/batiments-publics-equipes-de-defibrillateurs-a-paris/)
 - [x] [saint malo](https://www.data.gouv.fr/fr/datasets/defibrillateurs-1/)
 - [x] [toulouse](https://www.data.gouv.fr/fr/datasets/localisation-des-defibrillateurs-toulouse/)
 - [ ] [toulouse](https://www.data.gouv.fr/fr/datasets/defibrillateurs-tm/)
 - [ ] [daemap](https://www.data.gouv.fr/fr/datasets/defibrillateurs-publics/)
 - [ ] [cantal](https://www.data.gouv.fr/fr/datasets/defibrillateur-semi-automatique-571907/)
 - [ ] [boé](https://www.data.gouv.fr/fr/datasets/defibrillateurs-8/)
 - [ ] [castelnaudary](https://www.data.gouv.fr/fr/datasets/defibrillateurs-10/)
 - [ ] [meudon](https://www.data.gouv.fr/fr/datasets/defibrillateurs-7/)
 - [ ] [montpellier](https://www.data.gouv.fr/fr/datasets/defibrillateurs-6/)
 - [ ] [besançon](https://www.data.gouv.fr/fr/datasets/defibrillateurs-de-besancon/)

**Comment by frodrigo** [comment]
Partir d'un exemple, tous les analyse_merge* sont de l'opendata:
https://github.com/osm-fr/osmose-backend/tree/master/analysers
Typiquement : https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_police_FR_pn.py

Pour développer il y a l’environnement Docker:
https://github.com/osm-fr/osmose-backend/tree/master/docker

**Comment by deuzeffe** [comment]
@wadouk Pour le 87, il y a un fichier en OD sur la plateforme régionale. Mais je ne sais pas comment l'intégrer à ta carte mapcontrib :/

**Comment by wadouk** [comment]
@deuzeffe rajoute le lien ici, je le rajouterais dans l'analyse.
mais sinon je te rajoute en administrateurs sur la carte et tu pourras le faire aussi sur mapcontrib.
ps : c'est fait

**Comment by deuzeffe** [comment]
@wadouk grumpf, plus de téléchargement direct :/ À partir de https://www.sigena.fr/geonetwork/srv/fre/catalog.search#/metadata/1e113a13-1865-43da-b027-d8abeafbf2dd j'ai sorti un geojson en mercator : https://telecarto.sigena.fr/DOWNLOAD/Telechargement_1567627958_1320.zip Pas sure qu'il reste longtemps dispo...

Merci pour l'admin, je vais voir ça !

**Comment by wadouk** [comment]
J'ai voulu commencé avec le jeu de donnée sur paris, mais j'ai deux soucis : l'encodage et les champs qui contiennent des retours chariots. 
`psycopg2.errors.BadCopyFileFormat: unterminated CSV quoted field` 

Y aurait-il un moyen pour contourner le deuxième problème ? parce qu'il semble que ce soit postgre qui refuse.
https://www.postgresql.org/message-id/10837.1403211919%40sss.pgh.pa.us

**Comment by wadouk** [comment]
Et concernant l'analyse pour la Haute Vienne, c'est un fichier dans un zip, et c'est l'un des fichiers qui est dedans qu'il faut prendre. J'ai du mal à voir comment faire.

**Comment by frodrigo** [comment]
Pour le CSV. Il a le paramètre quote: https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge.py#L398
Le fichier CSV est un fichier CSV valide, ou non ?

S'il est invalide il y a moyen de la modifier avant de le charger
https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge.py#L310
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_school_FR.py#L60
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_heritage_FR_merimee.py#L71

**Comment by frodrigo** [comment]
Pour le ZIP, il faut utiliser le paramètre zip :
https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge.py#L308
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_parking_FR_capp.py#L33

**Comment by wadouk** [comment]
> Pour le CSV. Il a le paramètre quote: https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge.py#L398
> Le fichier CSV est un fichier CSV valide, ou non ?
> 
Il est valide, il se charge dans libre office, ou sur data.gouv.fr. Le problème c'est le champs multi ligne (avec des retours chariots et des quote, pas juste pour échapper les séparateurs de champs mais aussi ceux de ligne).
Je vais voir pour utiliser le paramètre filter

**Comment by frodrigo** [comment]
Regarde si un copy postgres peut le charger. Dans ce cas il faut corriger
osmose.

**Comment by frodrigo** [comment]
First results:
http://osmose.openstreetmap.fr/fr/errors/?item=8370,8371,8372&useDevItem=all

But we mixed with radio support.

**Comment by wadouk** [comment]
Oups, I could change to an other code

**Comment by frodrigo** [comment]
I already move the radio support.

**Comment by wadouk** [comment]
And how to display in pick lists the new codes ?

**Comment by frodrigo** [comment]
It is manual operation when we are good with the results.
Never the less you can have it from http://osmose.openstreetmap.fr/fr/errors/?item=8370,8371,8372&useDevItem=all (Carte link)

**Comment by frodrigo** [comment]
Have you checked the first results? Can we make this results public on the Osmose frontend? Once item enabled publicly the nexts analyser will be automatically visible on Osmose frontend.

**Comment by wadouk** [comment]
Except for issy les moulineaux for which I already made a fix on conflation distance (i have'nt look after enough precisely when you ask me), the others seems good. could be fixed as separate.
I have checked, not very precisely but had a look, on the mapcontrib and it's seems to make the work, for the first version.
Maybe later I will add some other things to check the opening hours or other attributes that open data give.
What points do you check in general before publishing ?

**Comment by frodrigo** [comment]
Just overview, open marker popups and make some fix myself.

**Comment by wadouk** [comment]
I just had a look on [overpass](http://overpass-turbo.eu/s/MXT) to see what is already done. There is some falsy : I just compare with nodes but there is some relations or ways (mairie du 12ème or the public libraries). Any pointer to compare throw all types ?

**Comment by frodrigo** [comment]
List the types here.
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_defibrillators_FR_basrhin.py#L38

**Comment by Bibi56** [comment]
@wadouk, if you want 893 (more): https://www.data.gouv.fr/fr/datasets/defibrillateurs-publics/#community-resources (ODbL).
But according to the wiki, you should stick to nodes.

**Comment by frodrigo** [comment]
Maybe an other analyser to report  where there are not on node?

**Comment by wadouk** [comment]
@Bibi56 it's planned to https://github.com/osm-fr/osmose-backend/issues/656
@frodrigo it's the direction it should be to make conflation on all types and make an other analysis to say "defibrillators should be node, position should be precised"

**Comment by frodrigo** [comment]
@wadouk Got this issue http://buildbot.osmose.openstreetmap.fr/builders/france_limousin_haute_vienne/builds/222/steps/osmose_run.py/logs/stdio
```
2019-10-13 04:16:45 france_limousin_haute_vienne : merge_defibrillators_FR_hautevienne
2019-10-13 04:16:45   error: Fails to get status from frontend: 404
2019-10-13 04:16:45   run osmosis all analyser Analyser_merge_defibrillators_FR_hautevienne
2019-10-13 04:16:45   error: error on analyse merge_defibrillators_FR_hautevienne...
2019-10-13 04:16:45     Traceback (most recent call last):
2019-10-13 04:16:45       File "./osmose_run.py", line 228, in execc
2019-10-13 04:16:45         analyser_obj.analyser()
2019-10-13 04:16:45       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 184, in analyser
2019-10-13 04:16:45         self.error_file.analyser(self.timestamp(), self.analyser_version())
2019-10-13 04:16:45       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 862, in analyser_version
2019-10-13 04:16:45         return SourceVersion.version(self.parser.source.time(), self.__class__)
2019-10-13 04:16:45       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 334, in time
2019-10-13 04:16:45         date_time = zipfile.ZipFile(f, 'r').getinfo(self.zip).date_time
2019-10-13 04:16:45       File "/usr/lib/python2.7/zipfile.py", line 912, in getinfo
2019-10-13 04:16:45         'There is no item named %r in the archive' % name)
2019-10-13 04:16:45     KeyError: "There is no item named u'Telechargement_1557715540_4003/1e113a13-1865-43da-b027-d8abeafbf2dd_1557715540_3898/dae_sdis87.shp' in the archive"
```

**Comment by wadouk** [comment]
The name is changing... could you deactivate the analysis ? Any way to execute a function to filter the files in the archive and found the good one ?

**Comment by frodrigo** [comment]
We can try get a file from the zip using a pattern https://github.com/osm-fr/osmose-backend/blob/master/analysers/Analyser_Merge.py#L352

**Comment by deuzeffe** [comment]
@wadouk Maybe have you already found the "official" repository : https://www.data.gouv.fr/fr/datasets/defibrillateur-automatise-externe-dae-haute-vienne/ ?

**Comment by wadouk** [comment]
I saw this one but I remember that the file in archive is complicated the same. Maybe i'm wrong. If someone wants to investigate, I could not have a look before this evening or tomorrow.

**Comment by wadouk** [comment]
with the link given by @deuzeffe it will be easy to make something that just works

**Comment by wadouk** [comment]
ping @frodrigo by the way, the already done analysis could be publicly available. do you have any limitation to already done analysis ?

**Comment by frodrigo** [comment]
Yes. Sorry we forgot.
@jocelynj can you enable items 8370,8371,8372
http://osmose.openstreetmap.fr/en/errors/?item=8370,8371,8372&useDevItem=all

**Comment by frodrigo** [comment]
The item is now public.

**Comment by frodrigo** [comment]
New error
http://buildbot.osmose.openstreetmap.fr/builders/france_bretagne_ille_et_vilaine/builds/230/steps/osmose_run.py/logs/stdio
```2019-10-21 06:49:31 france_bretagne_ille_et_vilaine : merge_defibrillators_FR_saintmalo
2019-10-21 06:49:31   run osmosis all analyser Analyser_merge_defibrillators_FR_saintmalo
2019-10-21 06:49:31   Analyser_Merge.py:883 sql
2019-10-21 06:49:31   Analyser_Merge.py:629 sql
2019-10-21 06:49:31   Analyser_Merge.py:634 sql
2019-10-21 06:49:31   Load source into database
2019-10-21 06:49:31   Analyser_Merge.py:637 sql
2019-10-21 06:49:31   error: error on analyse merge_defibrillators_FR_saintmalo...
2019-10-21 06:49:31     Traceback (most recent call last):
2019-10-21 06:49:31       File "./osmose_run.py", line 228, in execc
2019-10-21 06:49:31         analyser_obj.analyser()
2019-10-21 06:49:31       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 192, in analyser
2019-10-21 06:49:31         self.analyser_osmosis_common()
2019-10-21 06:49:31       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 884, in analyser_osmosis_common
2019-10-21 06:49:31         table = self.load.run(self, self.parser, self.mapping, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2019-10-21 06:49:31       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 639, in run
2019-10-21 06:49:31         header = parser.header()
2019-10-21 06:49:31       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 421, in header
2019-10-21 06:49:31         return csv.reader(self.f, delimiter=self.separator, quotechar=self.quote).next()
2019-10-21 06:49:31       File "/usr/lib/python2.7/dist-packages/backports/csv.py", line 232, in __init__
2019-10-21 06:49:31         raise TypeError(*e.args)
2019-10-21 06:49:31     TypeError: "delimiter" must be string, not bytes
2019-10-21 06:49:31   Closing reader and parser

```

**Comment by wadouk** [comment]
Strange to see that is works in previous runs : 
 - 218 OK 
 - 219 Err 500 on backend
 - 220 Err on delimiter
 - 222 OK
 - 223 Err on other thing
 - 228 OK

How do you check ? grep on logs and email when matching ?

In fact, i changed with putting the u and will push a merge request.

**Comment by frodrigo** [comment]
Not all backend have the same configuration, some in py2, some in py3.
Thank for the fix.
We recive email on fail.

**Comment by wadouk** [comment]
And this syntax with u is optional in python2 and mandatory in python 3 ?

**Comment by frodrigo** [comment]
New error
```
2019-11-02 05:51:12 france_midi_pyrenees_haute_garonne : merge_defibrillators_FR_toulouse
2019-11-02 05:51:12   run osmosis all analyser Analyser_merge_defibrillators_FR_toulouse
2019-11-02 05:51:14   Analyser_Merge.py:883 sql
2019-11-02 05:51:14   Analyser_Merge.py:629 sql
2019-11-02 05:51:14   Analyser_Merge.py:634 sql
2019-11-02 05:51:14   Load source into database
2019-11-02 05:51:14   Analyser_Merge.py:637 sql
2019-11-02 05:51:14   Analyser_Merge.py:645 sql
2019-11-02 05:51:14   Analyser_Merge.py:647 sql
2019-11-02 05:51:14   error: error on analyse merge_defibrillators_FR_toulouse...
2019-11-02 05:51:14     Traceback (most recent call last):
2019-11-02 05:51:14       File "./osmose_run.py", line 228, in execc
2019-11-02 05:51:14         analyser_obj.analyser()
2019-11-02 05:51:14       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 192, in analyser
2019-11-02 05:51:14         self.analyser_osmosis_common()
2019-11-02 05:51:14       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 884, in analyser_osmosis_common
2019-11-02 05:51:14         table = self.load.run(self, self.parser, self.mapping, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2019-11-02 05:51:14       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 648, in run
2019-11-02 05:51:14         parser.import_(table, self.srid, osmosis)
2019-11-02 05:51:14       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 520, in import_
2019-11-02 05:51:14         values.append(row['geometry']['coordinates'][1])
2019-11-02 05:51:14     IndexError: list index out of range
```
http://buildbot.osmose.openstreetmap.fr/builders/france_midi_pyrenees_haute_garonne/builds/242/steps/osmose_run.py/logs/stdio

**Comment by wadouk** [comment]
It seems that the data source change from Point to MulitPoint of size 1.
I thougt to remember that I have already done this kind of transformation but don't succeed to find it.
I will just this this file instead of Analyser_Merge.GeoJSON to handle this both types.

**Comment by wadouk** [comment]
I have to fix it in analyser_merge:520 because fixing it in Load is too late. It has already failed before.

**Comment by Bibi56** [comment]
If you do it from a PostGIS database (I doubt)  you can use [ST_GeometryN](https://postgis.net/docs/ST_GeometryN.html), otherwise you've to find a similar function.

**Comment by frodrigo** [comment]
Load the full GeoJson geometry with ST_GeomFromGeoJSON.
Then get only the first point or a centroid of the geometry like this https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_defibrillators_FR_hautevienne.py#L35

**Comment by frodrigo** [comment]
Reopen if required.
