### ISSUE TITLE
merge_defibrillators_FR_basrhin - 404

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#745]
```
2020-01-27 08:26:40 france_alsace_bas_rhin : merge_defibrillators_FR_basrhin
2020-01-27 08:26:43   run osmosis all analyser Analyser_merge_defibrillators_FR_basrhin
2020-01-27 08:26:44   error: error on analyse merge_defibrillators_FR_basrhin...
2020-01-27 08:26:44     Traceback (most recent call last):
2020-01-27 08:26:44       File "./osmose_run.py", line 230, in execc
2020-01-27 08:26:44         analyser_obj.analyser()
2020-01-27 08:26:44       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 184, in analyser
2020-01-27 08:26:44         self.error_file.analyser(self.timestamp(), self.analyser_version())
2020-01-27 08:26:44       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 885, in analyser_version
2020-01-27 08:26:44         return SourceVersion.version(self.parser.source.time(), self.__class__)
2020-01-27 08:26:44       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 346, in time
2020-01-27 08:26:44         return int(downloader.urlmtime(self.fileUrl, self.fileUrlCache)+.5)
2020-01-27 08:26:44       File "/data/project/osmose/backend/modules/downloader.py", line 125, in urlmtime
2020-01-27 08:26:44         return os.stat(update_cache(url, delay)).st_mtime
2020-01-27 08:26:44       File "/data/project/osmose/backend/modules/downloader.py", line 103, in update_cache
2020-01-27 08:26:44         if not fetch(url, tmp_file, date_string):
2020-01-27 08:26:44       File "/data/project/osmose/backend/modules/downloader.py", line 72, in http_get
2020-01-27 08:26:44         answer.raise_for_status()
2020-01-27 08:26:44       File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
2020-01-27 08:26:44         raise HTTPError(http_error_msg, response=self)
2020-01-27 08:26:44     requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://www.data.gouv.fr/fr/datasets/r/40f84199-8b19-492d-9f61-45156ac73b63
2020-01-27 08:26:44   Closing reader and parser
```

**Comment by frodrigo** [comment]
cc @wadouk

**Comment by wadouk** [comment]
https://www.data.gouv.fr/fr/datasets/r/b84312e9-b198-4f1d-b2ad-8e4df5b7cb5b

depuis https://www.data.gouv.fr/fr/datasets/donnee-thematique-localisation-des-defibrillateurs-automatiques-externes-dae-bas-rhin/

**Comment by frodrigo** [comment]
Please, can you make a PR?

**Comment by wadouk** [comment]
of course, i will try it, but don't know when i will could make it, and at least test one time.

that's why i had put the link

**Comment by frodrigo** [comment]
Done.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?item=8370&class=20
