### ISSUE TITLE
ModuleNotFoundError: No module named 'transporthours'

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#835]
cc @didier2020 

i've just installed a backend for test :
osmose_run.py --country=france_picardie_oise --analyser=sax
```
20-04-13 13:04:35     init TagFix_Housenumber (node, way, relation)
2020-04-13 13:04:35   Closing reader and parser
2020-04-13 13:04:35   error: error on analyse sax...
2020-04-13 13:04:35     Traceback (most recent call last):
2020-04-13 13:04:35       File "osmose_run.py", line 230, in execc
2020-04-13 13:04:35         analyser_obj.analyser()
2020-04-13 13:04:35       File "/home/didier/osmose-backend-master/analysers/analyser_sax.py", line 62, in analyser
2020-04-13 13:04:35         self._load_plugins()
2020-04-13 13:04:35       File "/home/didier/osmose-backend-master/analysers/analyser_sax.py", line 444, in _load_plugins
2020-04-13 13:04:35         pluginModule = importlib.import_module("plugins."+pluginName)
2020-04-13 13:04:35       File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
2020-04-13 13:04:35         return _bootstrap._gcd_import(name[level:], package, level)
2020-04-13 13:04:35       File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2020-04-13 13:04:35       File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2020-04-13 13:04:35       File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2020-04-13 13:04:35       File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2020-04-13 13:04:35       File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2020-04-13 13:04:35       File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-04-13 13:04:35       File "/home/didier/osmose-backend-master/plugins/TagFix_IntervalConditional.py", line 22, in <module>
2020-04-13 13:04:35         from transporthours.main import Main
2020-04-13 13:04:35     ModuleNotFoundError: No module named 'transporthours'

```
and the result xml is empty. on frontend these is 16 issues.

**Comment by jocelynj** [comment]
@didier2020: did you install the dependencies from requirements.txt?

**Comment by didier2020** [comment]
je pense que le probleme vient de (moi ?) avec l'installation pip (python3 vs 2.7)
transporthours est  dans /usr/local/lib/python2.7/dist-packages
(j'ai le meme probleme avec antlr4)
=> j'ai ajouté un lien symbolique vers /usr/lib/python3.7/dist-packages

**Comment by didier2020** [comment]
virtualenv was not installed...

**Comment by frodrigo** [comment]
I advise you to use the docker setup.

**Comment by didier2020** [comment]
I thought about it but I thought it would be easier directly as I do not know docker...

i confirm no error in osmose.

**Comment by frodrigo** [comment]
No, Docker was primary made to easier install.
