### ISSUE TITLE
Need help for analyser merge milestone

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-backend#893]
Hi,
it's about merging data from data.gouv.fr. 
i started to write a part of analyser merge ... I am not sure that this is correct .

```
class Analyser_Merge_Milestone_FR_metropole(Analyser_Merge):
    def __init__(self, config, logger = None):
        Analyser_Merge.__init__(self, config, logger)

        # fix item 
        self.def_class_missing_official(item = 8130, id = 41, level = 3, tags = ['merge', 'milestone'],
            title = T_('Milestone not integrated'))
        self.def_class_possible_merge(item = 8131, id = 43, level = 3, tags = ['merge', 'milestone'],
            title = T_('Milestone integration suggestion'))
        self.def_class_update_official(item = 8132, id = 44, level = 3, tags = ['merge', 'milestone'],
            title = T_('Milestone update'))

        def transform_to_natref(res1):
            #dept must be on 2 caracter
            dept=res1['depPr']
            if len(dept) == 1 :
                dept = '0' + dept
            if (dept in ('975','976','977')) :
                #proj is in utm
                return None
            elif (dept==res1['route'][0:2]) :
                #not a milestone but highway junction
                return None
            else :
                return dept + 'PR' + res1['pr'] + res1['cote'] + res1['concessionPr']

        def transform_route(res2):
            route=res2['route']
            #remove multiple 0 and add space
            if route[0:4] in ('A000', 'N000') : return route[0:1]+" "+route[5:]
            elif route[0:3] in ('A00', 'N00') : return route[0:1]+" "+route[4:]
            elif route[0:2] in ('A0', 'N0')   : return route[0:1]+" "+route[3:]
            elif route[0:1] in ('A', 'N')     : return route[0:1]+" "+route[2:]

        self.init(
            u"https://www.data.gouv.fr/fr/datasets/bornage-du-reseau-routier-national/",
            u"Bornage du réseau routier national",
            CSV(Source(u"data.gouv.fr:Ministère de la Transition écologique et solidaire", millesime = "01/2019",
                    fileUrl = u"https://www.data.gouv.fr/fr/datasets/r/fbc8b73b-a65c-486b-a710-ed22b9e4070c",
                    filter = lambda text: text.replace(',', '.')), separator = u"\t"),
                    
            Load("x", "y",srid = 2154,
                # if dept data from config.db ?
                select = {"depPr": u"80"},
                where = lambda row: transform_to_natref is not None),
            Mapping(
                select = Select(
                    types = ["nodes"],
                    tags = [{"highway": "milestone"}]),
                osmRef = "nat_ref",    
                conflationDistance = 300,
                generate = Generate(
                    static1 = {"highway": "milestone"},
                    static2 = {"source": self.source},
                    mapping1 = {
                        "distance": 'pr',
                        "nat_ref": lambda res1: transform_to_natref,
                        "ref": lambda res2: transform_route },
                        
                    text = '? ? ? ' )))

```

**Comment by didier2020** [comment]
backend error :
`
2020-05-29 16:02:21   Analyser_Merge.py:1009 sql
2020-05-29 16:02:21   Analyser_Merge.py:1011 xml generation
2020-05-29 16:02:21   error: res=['<function Analyser_Merge_Milestone_FR_metropole.__init__.<locals>.transform_to_natref at 0x7f5eb2d05840>', 'POINT(1.82676016098255 50.1309925589741)', {'ref': '<function Analyser_Merge_Milestone_FR_metropole.__init__.<locals>.transform_route at 0x7f5eb2d059d8>', 'source': 'data.gouv.fr:Ministère de la Transition écologique et solidaire - 01/2019', 'highway': 'milestone', 'nat_ref': '<function Analyser_Merge_Milestone_FR_metropole.__init__.<locals>.transform_to_natref at 0x7f5eb2d05840>', 'distance': '0'}, {'x': '616024.98', 'y': '7004263.88', 'z': '0', '_x': '616024.98', '_y': '7004263.88', 'pr': '0', 'abs': '0', 'cote': 'G', 'cumul': '0', 'depPr': '80', 'route': 'A0028', 'concessionPr': 'N', 'dateReferentiel': '2019-01-01'}, '0101000020E610000057E4D0DC683AFD3F14683A5DC4104940']
2020-05-29 16:02:21   error: ret=None
2020-05-29 16:02:21   error: error on analyse merge_milestone_FR_metropole...
2020-05-29 16:02:21     Traceback (most recent call last):
2020-05-29 16:02:21       File "./osmose_run.py", line 248, in execc
2020-05-29 16:02:21         analyser_obj.analyser()
2020-05-29 16:02:21       File "/data/osmose-backend-master/analysers/Analyser_Osmosis.py", line 193, in analyser
2020-05-29 16:02:21         self.analyser_osmosis_common()
2020-05-29 16:02:21       File "/data/osmose-backend-master/analysers/Analyser_Merge.py", line 1011, in analyser_osmosis_common
2020-05-29 16:02:21         self.run(sql12, lambda res: {
2020-05-29 16:02:21       File "/data/osmose-backend-master/analysers/Analyser_Osmosis.py", line 463, in run
2020-05-29 16:02:21         self.run00(sql, callback_package)
2020-05-29 16:02:21       File "/data/osmose-backend-master/analysers/Analyser_Osmosis.py", line 428, in run00
2020-05-29 16:02:21         ret = callback(res)
2020-05-29 16:02:21       File "/data/osmose-backend-master/analysers/Analyser_Osmosis.py", line 441, in callback_package
2020-05-29 16:02:21         ret = callback(res)
2020-05-29 16:02:21       File "/data/osmose-backend-master/analysers/Analyser_Merge.py", line 1016, in <lambda>
2020-05-29 16:02:21         "text": self.mapping.generate.text(defaultdict(lambda:None,res[2]), defaultdict(lambda:None,res[3])),
2020-05-29 16:02:21     TypeError: 'str' object is not callable
2020-05-29 16:02:21 cleaning : 

`

**Comment by frodrigo** [comment]
Open a PR, so we can comment on the code.

**Comment by didier2020** [comment]
thanks,
it's done there : 
https://github.com/didier2020/osmose-backend/commit/33ae931e58d1790d28839190b257fa5b7666038b

with sub_analyser or ?,
I want to take information from a first csv to use it in the second

**Comment by frodrigo** [comment]
Open a pull request with this branch.

**Comment by didier2020** [comment]
i had to understand git ... so i learn this (https://rogerdudler.github.io/git-guide/index.fr.html) before .

**Comment by frodrigo** [comment]
Is not a git feature. but a github one.
Just click on the green button front your branch on github.
You where close, but your delete it.
