### ISSUE TITLE
IT Fuel error

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#955]
The Fuel IT Open Data merge now fails. The source should have change.

https://buildbot.osmose.openstreetmap.fr/#/builders/300/builds/8/steps/1/logs/stdio
```
2020-08-25 14:52:08   error: error on analyse merge_fuel_IT...
2020-08-25 14:52:08     Traceback (most recent call last):
2020-08-25 14:52:08       File "./osmose_run.py", line 248, in execc
2020-08-25 14:52:08         analyser_obj.analyser()
2020-08-25 14:52:08       File "/data/project/osmose/backend/analysers/Analyser_Osmosis.py", line 193, in analyser
2020-08-25 14:52:08         self.analyser_osmosis_common()
2020-08-25 14:52:08       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 968, in analyser_osmosis_common
2020-08-25 14:52:08         table = self.load.run(self, self.parser, self.mapping, self.config.db_user, self.__class__.__name__.lower()[15:], self.analyser_version())
2020-08-25 14:52:08       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 666, in run
2020-08-25 14:52:08         header = parser.header()
2020-08-25 14:52:08       File "/data/project/osmose/backend/analysers/Analyser_Merge.py", line 423, in header
2020-08-25 14:52:08         self.f = self.source.open()
2020-08-25 14:52:08       File "/data/project/osmose/backend/analysers/analyser_merge_fuel_IT.py", line 97, in open
2020-08-25 14:52:08         return open(downloader.update_cache('join://' + self.source.fileUrl, 60, self.fetch))
2020-08-25 14:52:08       File "/data/project/osmose/backend/analysers/modules/downloader.py", line 98, in update_cache
2020-08-25 14:52:08         if not fetch(url, tmp_file, date_string):
2020-08-25 14:52:08       File "/data/project/osmose/backend/analysers/analyser_merge_fuel_IT.py", line 111, in fetch
2020-08-25 14:52:08         carburante = self.FUEL_TYPE_MAP.get(row[1].upper())
2020-08-25 14:52:08     IndexError: list index out of range
```

cc @fansanelli

**Comment by fansanelli** [comment]
Dear @frodrigo 

I checked the dataset and didn't spot any obvious change...
The format is still the same and the FUEL_TYPE_MAP too ("Excellium diesel" is a new entry, but the upper() will normalize it).
I can run the analyzer on my machine this weekend and try to address this issue, if nobody beats me.

Thanks
Francesco

**Comment by frodrigo** [comment]
I see in logs its now OK. It may be a temporary error.
