### ISSUE TITLE
Exception: KeyError: "'like'" in OsmoseTranslation.py", line 95, in translate_format

### ISSUE THREAD

**Issue by stephankn** [osm-fr/osmose-backend#958]
version commit c6196d86eb8912644e4d3b2f39ac1bad547a73d0

affects all analyzed countries. All come up with 

```
2020-08-28 02:02:31   error: error on analyse merge_traffic_signs...
2020-08-28 02:02:31     Traceback (most recent call last):
2020-08-28 02:02:31       File "./osmose_run.py", line 243, in execc
2020-08-28 02:02:31         if analyser_obj.timestamp() and remote_timestamp and analyser_obj.timestamp() <= remote_timestamp:
2020-08-28 02:02:31       File "/opt/osmose-backend/analysers/Analyser_Merge_Dynamic.py", line 49, in timestamp
2020-08-28 02:02:31         with self.analysers[0](self.config, self.error_file,  self.logger) as analyser_obj:
2020-08-28 02:02:31       File "/opt/osmose-backend/analysers/Analyser_Merge_Dynamic.py", line 31, in __init__
2020-08-28 02:02:31         classs.__init__(self, config, error_file, logger, *args)
2020-08-28 02:02:31       File "/opt/osmose-backend/analysers/analyser_merge_traffic_signs.py", line 81, in __init__
2020-08-28 02:02:31         detail = T_f('Traffic sign ({1}) detected by Mapillary, but no nearby tagging of any:{0}', '\n\n- ' + '\n- '.join(missing_tags), T_(title)),
2020-08-28 02:02:31       File "/opt/osmose-backend/modules/OsmoseTranslation.py", line 95, in translate_format
2020-08-28 02:02:31         out["en"] = out["en"].format(*map(lambda a: a['en'], args_translated))
2020-08-28 02:02:31     KeyError: "'like'"
```

Regression after this:
https://github.com/osm-fr/osmose-backend/commit/b827b2f61f40f9e6b74fea2044c28d8095648a8d

**Comment by stephankn** [comment]
@frodrigo can you please have a look?

**Comment by frodrigo** [comment]
I see, but not looker into it, yet.
Linked with yesterday update.
